// ---------------------------------------------------------------------------
// Linux_SystemSetting.mof
//
// Copyright (c) IBM Corp. 2004, 2009
//
// THIS FILE IS PROVIDED UNDER THE TERMS OF THE ECLIPSE PUBLIC LICENSE
// ("AGREEMENT"). ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS FILE
// CONSTITUTES RECIPIENTS ACCEPTANCE OF THE AGREEMENT.
//
// You can obtain a current copy of the Eclipse Public License from
// http://www.opensource.org/licenses/eclipse-1.0.php
//
// Author:	Dr. Gareth S. Bestor <bestorga@us.ibm.com>
// Description:	Linux_SystemSetting mof template
// Interface:	Common Manageability Programming Interface (CMPI)
//
// IMPORTANT: This file must be renamed to the desired new
// Linux_SystemSetting instance provider mof; e.g.
//	mv Linux_SystemSetting.mof Linux_NFSv3SystemSetting.mof
// Then change all occurances of "Linux_SystemSetting" in this file to,
// say, "Linux_NFSv3SystemSetting".
// Then add all of the new class's properties and their CIM types to the 
// end of this class definition.
// DO NOT CHANGE ANY OF THE EXISTING PROPERTIES!
// ---------------------------------------------------------------------------

#pragma locale ("en_US")

[Description
	("NFSv3 configuration file /etc/exports settings"),
 Provider("cmpi:Linux_NFSv3SystemSetting") ]
class Linux_NFSv3SystemSetting : CIM_SystemSetting
{
   // Linux_SystemSetting Key Properties 

   [Propagated ("CIM_System.Name"),
    Key, MaxLen (256),
    Description
	("The scoping System's Name.") ]
   string SystemName;

   [Propagated ("CIM_System.CreationClassName"),
    Key, MaxLen (256),
    Description 
	("The scoping System's CreationClassName.") ]
   string SystemCreationClassName;

   [Propagated ("CIM_SystemSetting.CreationClassName"),
    Key, MaxLen (256),
    Description
	("CreationClassName indicates the name of the class or the subclass used "
	 "in the creation of an instance. When used with the other key properties "
	 "of this class, this property allows all instances of this class and its "
	 "subclasses to be uniquely identified.") ]
   string CreationClassName;

   [Propagated ("CIM_SystemSetting.SettingID"),
    Key, MaxLen (256),
    Description
	("The identifier by which the Setting object is known.")]
   string SettingID;


   // Linux_SystemSetting Config File Properties 

   [Propagated ("CIM_LogicalFile.Name"),
    Description
	("Name of the actual configuration file storing this setting.") ]
   string Filename;

   [Propagated ("CIM_LogicalFile.Readable"),
    Description
	("Boolean indicating if the configuration file can be read.") ]
   boolean Readable;

   [Propagated ("CIM_LogicalFile.Writeable"),
    Description
	("Boolean indicating if the configuration file can be written.") ]
   boolean Writeable;
  
   
   // Add Linux_SystemSetting Custom Properties Below... 

   [Description
	("This is the full pathname of the exported directory.") ]
   string Directory;

   [Description
	("This is the name/identifier of the remote host(s) that will be able to mount the directory.") ]
   string RemoteHost;

   [Description
	("Is the exported directory read-write (rw) or read-only (ro) by the client.") ]
   string Permission = "ro";

   [Description
	("If secure then mount requests must originate from a 'secure' Internet port; i.e. port# < IPPORT_RESERVED.") ]
   boolean Secure;

   [Description
	("User ID root mapping. Valid values are: root_squash, no_root_squash, all_squash.") ]
   string Squash;

   [Description
	("Commit all write operations to disk before the write request completes.") ]
   boolean Sync;

   [Description
	("Briefly postpone consecutive write operations. This only has an effect when Sync=true.") ]
   boolean Delay;

   [Description
	("Hide unmounted exported subdirectories even when their parent directory is mounted.") ]
   boolean Hide;

   [Description
	("Check for filesystem subtree access.") ]
   boolean SubtreeCheck;

   [Description
	("Require authentication of NLM locking requests.") ]
   boolean SecureLocks;

   [Description
	("Group ID for anonymous access.") ]
   uint16 AnonGID;

   [Description
	("User ID for anonymous access.") ]
   uint16 AnonUID;

   [Description
	("Crossmnt enabled if true") ]
   boolean Crossmnt;

   [Description
	("Valid values are: all_squash, no_all_squash") ]
   string AllSquash;

   [Description
	("Acl enabled if true") ]
   boolean Acl;
};

