
#line 3 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define NFSv3yyconst const
#else
#define NFSv3yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (NFSv3yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((NFSv3yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE NFSv3yyrestart(NFSv3yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(NFSv3yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct NFSv3yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int NFSv3yyleng;

extern FILE *NFSv3yyin, *NFSv3yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for NFSv3yy_rule_can_match_eol because it requires
     *       access to the local variable NFSv3yy_act. Since NFSv3yyless() is a macro, it would break
     *       existing scanners that call NFSv3yyless() from OUTSIDE NFSv3yylex. 
     *       One obvious solution it to make NFSv3yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-NFSv3yylineno scanner, because NFSv3yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int NFSv3yyl;\
                for ( NFSv3yyl = n; NFSv3yyl < NFSv3yyleng; ++NFSv3yyl )\
                    if ( NFSv3yytext[NFSv3yyl] == '\n' )\
                        --NFSv3yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define NFSv3yyless(n) \
	do \
		{ \
		/* Undo effects of setting up NFSv3yytext. */ \
        int NFSv3yyless_macro_arg = (n); \
        YY_LESS_LINENO(NFSv3yyless_macro_arg);\
		*NFSv3yy_cp = (NFSv3yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(NFSv3yy_c_buf_p) = NFSv3yy_cp = NFSv3yy_bp + NFSv3yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up NFSv3yytext again */ \
		} \
	while ( 0 )

#define unput(c) NFSv3yyunput( c, (NFSv3yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t NFSv3yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct NFSv3yy_buffer_state
	{
	FILE *NFSv3yy_input_file;

	char *NFSv3yy_ch_buf;		/* input buffer */
	char *NFSv3yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	NFSv3yy_size_t NFSv3yy_buf_size;

	/* Number of characters read into NFSv3yy_ch_buf, not including EOB
	 * characters.
	 */
	int NFSv3yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int NFSv3yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int NFSv3yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int NFSv3yy_at_bol;

    int NFSv3yy_bs_lineno; /**< The line count. */
    int NFSv3yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int NFSv3yy_fill_buffer;

	int NFSv3yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via NFSv3yyrestart()), so that the user can continue scanning by
	 * just pointing NFSv3yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t NFSv3yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t NFSv3yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * NFSv3yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (NFSv3yy_buffer_stack) \
                          ? (NFSv3yy_buffer_stack)[(NFSv3yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (NFSv3yy_buffer_stack)[(NFSv3yy_buffer_stack_top)]

/* NFSv3yy_hold_char holds the character lost when NFSv3yytext is formed. */
static char NFSv3yy_hold_char;
static int NFSv3yy_n_chars;		/* number of characters read into NFSv3yy_ch_buf */
int NFSv3yyleng;

/* Points to current character in buffer. */
static char *NFSv3yy_c_buf_p = (char *) 0;
static int NFSv3yy_init = 0;		/* whether we need to initialize */
static int NFSv3yy_start = 0;	/* start state number */

/* Flag which is used to allow NFSv3yywrap()'s to do buffer switches
 * instead of setting up a fresh NFSv3yyin.  A bit of a hack ...
 */
static int NFSv3yy_did_buffer_switch_on_eof;

void NFSv3yyrestart (FILE *input_file  );
void NFSv3yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE NFSv3yy_create_buffer (FILE *file,int size  );
void NFSv3yy_delete_buffer (YY_BUFFER_STATE b  );
void NFSv3yy_flush_buffer (YY_BUFFER_STATE b  );
void NFSv3yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void NFSv3yypop_buffer_state (void );

static void NFSv3yyensure_buffer_stack (void );
static void NFSv3yy_load_buffer_state (void );
static void NFSv3yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER NFSv3yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE NFSv3yy_scan_buffer (char *base,NFSv3yy_size_t size  );
YY_BUFFER_STATE NFSv3yy_scan_string (NFSv3yyconst char *NFSv3yy_str  );
YY_BUFFER_STATE NFSv3yy_scan_bytes (NFSv3yyconst char *bytes,int len  );

void *NFSv3yyalloc (NFSv3yy_size_t  );
void *NFSv3yyrealloc (void *,NFSv3yy_size_t  );
void NFSv3yyfree (void *  );

#define NFSv3yy_new_buffer NFSv3yy_create_buffer

#define NFSv3yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        NFSv3yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            NFSv3yy_create_buffer(NFSv3yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->NFSv3yy_is_interactive = is_interactive; \
	}

#define NFSv3yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        NFSv3yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            NFSv3yy_create_buffer(NFSv3yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->NFSv3yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->NFSv3yy_at_bol)

/* Begin user sect3 */

#define NFSv3yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *NFSv3yyin = (FILE *) 0, *NFSv3yyout = (FILE *) 0;

typedef int NFSv3yy_state_type;

#define YY_FLEX_LEX_COMPAT
extern int NFSv3yylineno;

int NFSv3yylineno = 1;

extern char NFSv3yytext[];

static NFSv3yy_state_type NFSv3yy_get_previous_state (void );
static NFSv3yy_state_type NFSv3yy_try_NUL_trans (NFSv3yy_state_type current_state  );
static int NFSv3yy_get_next_buffer (void );
static void NFSv3yy_fatal_error (NFSv3yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up NFSv3yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(NFSv3yytext_ptr) = NFSv3yy_bp; \
	NFSv3yyleng = (size_t) (NFSv3yy_cp - NFSv3yy_bp); \
	(NFSv3yy_hold_char) = *NFSv3yy_cp; \
	*NFSv3yy_cp = '\0'; \
	if ( NFSv3yyleng + (NFSv3yy_more_offset) >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	NFSv3yy_flex_strncpy( &NFSv3yytext[(NFSv3yy_more_offset)], (NFSv3yytext_ptr), NFSv3yyleng + 1 ); \
	NFSv3yyleng += (NFSv3yy_more_offset); \
	(NFSv3yy_prev_more_offset) = (NFSv3yy_more_offset); \
	(NFSv3yy_more_offset) = 0; \
	(NFSv3yy_c_buf_p) = NFSv3yy_cp;

#define YY_NUM_RULES 40
#define YY_END_OF_BUFFER 41
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct NFSv3yy_trans_info
	{
	flex_int32_t NFSv3yy_verify;
	flex_int32_t NFSv3yy_nxt;
	};
static NFSv3yyconst flex_int16_t NFSv3yy_acclist[265] =
    {   0,
       41,   39,   40,   36,   39,   40,   35,   40,   39,   40,
       29,   39,   40,   27,   39,   40,   34,   39,   40,   39,
       40,   39,   40,   28,   39,   40,   39,   40,   28,   39,
       40,   28,   39,   40,   28,   39,   40,   28,   39,   40,
       28,   39,   40,   28,   39,   40,   28,   39,   40,   28,
       39,   40,   36,   38,   27,   34,   33,   28,   37,   28,
       28,   28,   28,   28,   28,   28,   28,   28,    6,   28,
        5,   28,   28,   28,   28,   28,   30,   27,   27,   33,
       28,   30,   19,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   30,

       27,   28,   30,   28,   28,   28,   28,   28,   13,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
        9,   28,   28,   30,   27,   28,   30,   28,   28,   28,
       10,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   30,   28,   30,
       28,   28,   28,   28,   28,   28,   20,   28,   28,   28,
       28,   28,   28,   28,   14,   28,   28,    7,   28,   28,
       11,   28,   31,   28,    1,   28,    2,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   23,   28,   15,   28,    8,   28,   28,   28,   28,

       28,   28,   28,   28,   28,   28,   32,   28,   28,   28,
       28,   28,   28,   12,   28,   28,   28,   28,   28,   17,
       28,   28,   28,   28,   28,   28,   16,   28,   28,   28,
       28,   28,   28,   25,   28,   28,   28,    4,   28,   28,
       28,   28,   28,   28,   28,   24,   28,   28,   28,   18,
       28,   28,   28,   21,   28,   26,   28,    3,   28,   28,
       32,   28,   22,   28
    } ;

static NFSv3yyconst flex_int16_t NFSv3yy_accept[225] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   11,   14,   17,
       20,   22,   24,   27,   29,   32,   35,   38,   41,   44,
       47,   50,   53,   54,   54,   55,   55,   55,   56,   56,
       56,   57,   58,   59,   59,   60,   61,   62,   63,   64,
       65,   66,   67,   68,   69,   71,   73,   74,   75,   76,
       77,   78,   79,   80,   80,   81,   83,   85,   86,   87,
       88,   89,   90,   91,   92,   93,   94,   95,   96,   97,
       98,   99,  100,  101,  101,  102,  102,  104,  104,  105,
      106,  107,  108,  109,  111,  112,  113,  114,  115,  116,
      117,  118,  119,  120,  121,  123,  124,  125,  126,  126,

      128,  129,  130,  131,  133,  134,  135,  136,  137,  138,
      139,  140,  141,  142,  143,  144,  145,  146,  147,  148,
      149,  149,  151,  152,  153,  154,  155,  156,  157,  159,
      160,  161,  162,  163,  164,  165,  167,  168,  170,  171,
      173,  174,  175,  177,  179,  180,  181,  182,  183,  184,
      185,  186,  187,  188,  189,  190,  191,  191,  192,  194,
      196,  198,  199,  200,  201,  202,  203,  204,  205,  206,
      207,  208,  209,  210,  211,  212,  213,  214,  216,  217,
      218,  219,  220,  220,  222,  223,  224,  225,  226,  227,
      229,  230,  231,  232,  232,  233,  234,  236,  237,  238,

      240,  241,  242,  242,  243,  244,  245,  246,  248,  249,
      249,  250,  252,  253,  254,  256,  256,  258,  260,  261,
      262,  263,  265,  265
    } ;

static NFSv3yyconst flex_int32_t NFSv3yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    1,    1,    1,    1,    1,
        1,    5,    6,    1,    7,    8,    9,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,    1,    1,    1,
        1,    1,   11,   12,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
        1,   14,    1,    1,   15,    1,   16,   17,   18,   19,

       20,   13,   21,   22,   23,   13,   24,   25,   26,   27,
       28,   13,   29,   30,   31,   32,   33,   13,   34,   13,
       35,   13,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static NFSv3yyconst flex_int32_t NFSv3yy_meta[36] =
    {   0,
        1,    1,    1,    1,    2,    3,    4,    5,    6,    7,
        2,    1,    8,    1,    4,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8
    } ;

static NFSv3yyconst flex_int16_t NFSv3yy_base[241] =
    {   0,
        0,    0,  322,  844,  317,  844,  313,  304,  295,   28,
      293,    0,   32,  295,   39,   37,   48,   41,   50,   68,
       98,   69,  290,  279,  844,  269,    0,  264,  257,  249,
       31,    0,   76,    0,  844,   86,   87,   96,   80,   88,
       94,   97,  105,  126,  114,  117,   47,   68,  136,  133,
      237,  222,    0,  118,    0,  217,  136,  142,  152,  158,
      160,  166,  157,  163,  183,  171,  187,  191,  167,  195,
      171,  214,  211,    0,  200,  162,  157,    0,  190,  213,
      220,  222,  232,  234,  240,  242,  250,  241,  250,  251,
      261,  273,  275,  284,  285,  293,  154,  146,  135,  131,

      295,  303,  305,  314,  315,  323,  311,  315,  327,  323,
      331,  337,  341,  347,  348,  353,  357,  365,  369,  127,
      109,  102,  373,  376,  393,  385,  394,  402,  403,  379,
      424,  425,  426,  434,  445,  446,  451,  456,  442,  450,
      185,  466,  459,  467,  470,  475,  471,  478,  466,  497,
      499,  508,  510,  498,  502,  523,   95,  524,  525,  534,
      535,  536,  544,  545,  544,  548,  553,  554,  562,  576,
      233,  578,  584,  572,  583,  584,  590,  591,  595,  600,
      614,  619,   89,  624,  625,  633,  639,  625,  641,  649,
      651,  657,  650,  243,  662,  671,  672,  681,  673,  683,

      689,  691,   83,  697,  707,  708,  709,  718,  719,  279,
      720,  730,  731,  724,  727,   79,  730,  734,  746,   72,
      755,  756,  844,  779,  786,  790,   67,  797,   55,  803,
      805,   52,  810,  814,  819,   46,  825,   43,  830,  835
    } ;

static NFSv3yyconst flex_int16_t NFSv3yy_def[241] =
    {   0,
      223,    1,  223,  223,  223,  223,  224,  225,  226,  223,
      225,  227,  228,  223,  228,  228,  228,  228,  228,  228,
      228,  228,  223,  224,  223,  225,  229,  230,  226,  223,
      223,  231,  228,  232,  223,  228,  228,  228,   21,   21,
       21,   21,   21,   21,   21,   21,   44,   44,   44,   21,
      233,  230,  234,  223,  231,  235,   21,   44,   44,   44,
       44,   44,   21,   21,   21,   21,   21,   21,   21,   21,
       44,   44,  233,  236,  237,  223,  235,  238,   44,   21,
       44,   44,   44,   44,   44,   44,   44,   21,   21,   21,
       21,   44,   44,   44,   44,   44,  239,  237,  223,  240,

       44,   44,   44,   44,   44,   44,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,  239,
      223,  240,   21,   21,   21,   21,   21,   21,   21,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   21,   21,
      223,   21,   21,   21,   21,   21,   21,   21,   44,   44,
       44,   44,   44,   21,   21,   44,  223,   44,   44,   44,
       44,   44,   44,   44,   21,   21,   21,   21,   21,   44,
      223,   44,   44,   21,   21,   21,   21,   21,   21,   21,
       44,   44,  223,   44,   44,   44,   44,   21,   44,   44,
       44,   44,   21,  223,   44,   44,   44,   44,   44,   44,

       44,   44,  223,   44,   44,   44,   44,   44,   44,  223,
       44,   44,   44,   21,   21,  223,   21,   21,   44,  223,
       44,   44,    0,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223
    } ;

static NFSv3yyconst flex_int16_t NFSv3yy_nxt[880] =
    {   0,
        4,    5,    6,    7,    8,    4,    4,    4,    9,   10,
       11,   12,   13,   14,    4,   15,   13,   16,   13,   13,
       13,   17,   18,   13,   13,   13,   19,   13,   13,   20,
       21,   13,   13,   22,   13,   30,   26,   31,   30,   34,
       31,   26,   26,   26,   34,   26,   34,   26,   34,   26,
      100,   26,   26,   97,   26,   34,   36,   34,   26,   56,
       26,   33,   51,   37,   69,   38,   41,   43,   33,   39,
       42,   40,   26,   26,   32,   34,   34,   44,   26,   26,
       26,  220,   33,   34,   70,   33,   26,   50,  220,   33,
       26,   26,  210,   34,   34,   45,   26,   26,  194,   33,

       26,   46,   26,   34,  171,   34,   26,   33,   26,   78,
       57,   58,   33,   33,   60,   63,   33,   47,  141,   61,
       33,   62,   33,   59,   33,   76,   33,   54,   33,   33,
       48,   33,   49,   33,   74,   64,   33,   33,   78,   33,
       65,   68,  121,   66,   99,   33,   33,   67,   33,   33,
       33,   33,   72,   33,   53,   33,   79,   33,   33,   33,
       33,   74,   71,   33,   78,   33,   33,   33,   33,   33,
       33,   99,   33,   33,   33,   33,   84,   33,   80,   33,
       33,   82,   85,   33,   81,   33,   33,   33,   95,   33,
       33,   33,   33,  157,  141,   33,   83,   33,   86,   93,

       90,   33,   33,   33,   33,   33,   33,   33,   53,   91,
       33,   33,   87,   88,   33,   33,   89,   33,   74,   33,
      101,   33,   92,   33,   78,   33,   94,   33,   33,   33,
       53,   33,   33,  102,   33,   33,  105,  104,   96,   33,
      183,   33,  171,   33,   74,  103,   33,   33,   33,   33,
      203,   33,  194,   33,   33,   33,   33,  107,   54,  108,
       33,   33,  106,   33,   33,  223,  109,   33,  113,   33,
       33,   33,   53,  112,  110,   33,   27,  111,  114,  115,
       33,   25,   33,   33,   33,   33,  216,  116,  210,   33,
       33,   23,   33,   33,   33,   33,   33,   35,   33,   33,

       27,   33,   33,   29,  117,   33,   33,   33,  119,   33,
       33,   27,   33,  118,   33,   25,   33,   33,   23,   33,
       33,  223,   33,  123,   33,  124,   33,  125,   33,   33,
       33,   33,   33,  223,   33,   33,   33,   33,  223,  129,
       33,  126,   33,  128,   33,   33,   33,   33,  127,   33,
       33,  130,  223,  133,  131,   33,   33,   33,  132,   33,
      134,   33,  223,   33,  223,   33,   33,  136,  223,   33,
      223,   33,   33,   33,  223,   33,  138,  135,  223,   33,
       33,   33,   33,  137,  139,   33,  223,   33,   33,   33,
      223,   33,   33,  148,  143,   33,   33,   33,  223,   33,

       33,   33,  223,  140,   33,  142,  223,   33,   33,  145,
       33,  144,   33,   33,  223,  223,  223,   33,  223,   33,
      146,   33,   33,  223,  223,   33,   33,   33,   33,  223,
      223,  147,  223,  223,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,  223,  149,   33,   33,   33,  223,
      223,   33,  223,  223,  223,   33,  150,  151,  152,   33,
       33,  156,   33,   33,  223,   33,   33,   33,   33,   33,
      155,  223,   33,   33,   33,  153,   33,   33,   33,  154,
      163,  158,   33,   33,   33,   33,   33,   33,  223,   33,
      161,   33,  223,   33,   33,  159,  223,   33,   33,   33,

       33,   33,   33,   33,   33,   33,  160,   33,  162,   33,
       33,  164,   33,   33,   33,  223,   33,   33,   33,  223,
       33,   33,   33,  166,   33,   33,  169,   33,  165,   33,
      168,   33,   33,  223,   33,  167,   33,  170,   33,   33,
       33,   33,   33,  223,   33,   33,   33,  223,   33,  173,
       33,   33,   33,   33,  172,   33,   33,   33,   33,   33,
      223,   33,   33,  177,  174,   33,   33,   33,  223,  180,
      175,  223,   33,   33,  223,  176,   33,  223,   33,  179,
       33,   33,  178,  223,  223,   33,   33,   33,   33,  181,
       33,   33,   33,  182,   33,   33,   33,   33,   33,  184,

      223,   33,   33,   33,  186,   33,   33,  187,  185,  189,
       33,  223,  188,  223,   33,   33,   33,   33,   33,   33,
      223,  223,   33,   33,   33,   33,  190,   33,   33,   33,
      191,  192,   33,   33,   33,   33,   33,  223,   33,   33,
      193,   33,   33,  223,   33,   33,   33,   33,  196,  223,
       33,  223,  195,   33,   33,  199,   33,  198,   33,   33,
       33,  223,   33,   33,  197,   33,   33,  223,   33,  202,
       33,   33,  200,  223,   33,  223,   33,  223,   33,  204,
      201,  223,   33,   33,   33,   33,   33,   33,   33,   33,
      207,  223,   33,   33,   33,   33,  206,   33,   33,  223,

       33,  205,   33,   33,   33,   33,   33,  223,  209,  223,
       33,   33,   33,  223,   33,  223,  223,  223,   33,  208,
      211,   33,   33,   33,   33,   33,   33,  223,  212,   33,
      214,  223,   33,   33,   33,   33,   33,   33,  213,   33,
       33,   33,  215,  219,   33,   33,   33,   33,   33,   33,
      217,   33,  218,   33,  223,  223,   33,  223,   33,   33,
       33,   33,   33,  221,   33,  223,   33,   33,   33,   33,
       33,  223,   33,   33,  223,  223,   33,   33,  222,   24,
       24,   24,   24,   24,   24,   24,   24,   26,  223,   26,
       26,  223,   26,   26,   28,   28,   28,   28,   33,  223,

       33,   33,  223,   33,   33,   52,   52,   52,   52,   52,
       52,   55,   55,   73,   73,  223,   73,   73,   75,  223,
       75,   75,   77,   77,  223,   77,   77,   98,   98,   98,
       98,   98,   98,  120,  120,  223,  120,  120,  122,  122,
      223,  122,  122,    3,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223
    } ;

static NFSv3yyconst flex_int16_t NFSv3yy_chk[880] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   10,   13,   10,   31,   13,
       31,   16,   13,   15,   16,   18,   15,   16,   18,   15,
      238,   18,   17,  236,   19,   17,   15,   19,   17,  232,
       19,   47,  229,   15,   47,   15,   16,   18,   47,   15,
       17,   15,   20,   22,  227,   20,   22,   19,   20,   22,
       33,  220,   48,   33,   48,   48,   33,   22,  216,   48,
       36,   37,  203,   36,   37,   20,   36,   37,  183,   39,

       38,   20,   21,   38,  157,   21,   38,   40,   21,  122,
       36,   37,   39,   41,   39,   42,   42,   21,  121,   40,
       40,   41,   40,   38,   43,   54,   41,   54,   41,   42,
       21,   42,   21,   45,  120,   43,   46,   43,  100,   43,
       44,   45,   99,   44,   99,   44,   45,   44,   45,   46,
       49,   46,   50,   49,   98,   57,   58,   49,   44,   58,
       44,   97,   49,   58,   77,   50,   59,   50,   57,   59,
       57,   76,   60,   59,   61,   60,   63,   61,   59,   60,
       62,   61,   64,   62,   60,   71,   69,   62,   71,   63,
       66,   63,   71,  141,  141,   64,   62,   64,   65,   69,

       66,   69,   65,   66,   79,   66,   67,   79,   75,   67,
       68,   79,   65,   65,   70,   65,   65,   65,   73,   67,
       79,   67,   68,   68,   56,   68,   70,   70,   72,   70,
       52,   72,   80,   80,   81,   72,   82,   81,   72,   82,
      171,   81,  171,   82,   51,   80,   83,   80,   84,   83,
      194,   84,  194,   83,   85,   84,   86,   85,   30,   86,
       88,   85,   83,   86,   87,   29,   86,   87,   89,   89,
       90,   87,   28,   88,   86,   88,   26,   87,   90,   91,
       91,   24,   89,   90,   89,   90,  210,   92,  210,   93,
       92,   23,   93,   91,   92,   91,   93,   14,   94,   95,

       11,   94,   95,    9,   93,   94,   95,   96,   96,  101,
       96,    8,  101,   94,   96,    7,  101,  102,    5,  103,
      102,    3,  103,  101,  102,  102,  103,  103,  104,  105,
      107,  104,  105,    0,  108,  104,  105,  106,    0,  108,
      106,  105,  110,  107,  106,  107,  109,  108,  106,  108,
      111,  109,    0,  112,  110,  110,  112,  110,  111,  109,
      113,  109,    0,  111,    0,  111,  114,  115,    0,  112,
        0,  112,  116,  113,    0,  113,  117,  114,    0,  114,
      115,  114,  115,  116,  118,  116,    0,  116,  119,  117,
        0,  117,  123,  130,  124,  124,  130,  118,    0,  118,

      130,  119,    0,  119,  126,  123,    0,  123,  124,  126,
      124,  125,  125,  127,    0,    0,    0,  126,    0,  126,
      127,  128,  129,    0,    0,  125,  127,  125,  127,    0,
        0,  128,    0,    0,  128,  129,  128,  129,  131,  132,
      133,  131,  132,  133,    0,  131,  132,  133,  134,    0,
        0,  134,    0,    0,    0,  134,  132,  133,  134,  135,
      136,  139,  135,  136,    0,  137,  135,  136,  137,  140,
      138,    0,  137,  138,  139,  135,  139,  138,  143,  137,
      149,  142,  140,  149,  140,  142,  144,  149,    0,  145,
      147,  143,    0,  143,  146,  145,    0,  148,  142,  144,

      142,  144,  145,  147,  145,  147,  146,  146,  148,  146,
      148,  150,  148,  151,  150,    0,  151,  154,  150,    0,
      151,  155,  152,  152,  153,  152,  155,  153,  151,  152,
      154,  153,  154,    0,  155,  153,  155,  156,  158,  159,
      156,  158,  159,    0,  156,  158,  159,    0,  160,  161,
      162,  160,  161,  162,  158,  160,  161,  162,  163,  164,
        0,  163,  164,  165,  162,  163,  164,  166,    0,  168,
      163,    0,  167,  168,    0,  164,  165,    0,  165,  167,
      166,  169,  166,    0,    0,  167,  168,  167,  168,  169,
      170,  174,  172,  170,  169,  172,  169,  170,  173,  172,

        0,  173,  175,  176,  174,  173,  174,  175,  173,  177,
      178,    0,  176,    0,  179,  175,  176,  175,  176,  180,
        0,    0,  177,  178,  177,  178,  179,  179,  181,  179,
      180,  181,  180,  182,  180,  181,  182,    0,  184,  185,
      182,  184,  185,    0,  188,  184,  185,  186,  186,    0,
      186,    0,  185,  187,  186,  189,  187,  188,  189,  188,
      187,    0,  189,  190,  187,  191,  190,    0,  191,  193,
      190,  192,  191,    0,  192,    0,  195,    0,  192,  195,
      192,    0,  193,  195,  193,  196,  197,  199,  196,  197,
      199,    0,  196,  197,  199,  198,  198,  200,  198,    0,

      200,  196,  198,  201,  200,  202,  201,    0,  202,    0,
      201,  204,  202,    0,  204,    0,    0,    0,  204,  201,
      204,  205,  206,  207,  205,  206,  207,    0,  205,  206,
      207,    0,  208,  209,  211,  208,  209,  211,  206,  208,
      209,  211,  209,  214,  212,  213,  215,  212,  213,  217,
      211,  212,  213,  218,    0,    0,  214,    0,  214,  215,
      219,  215,  217,  219,  217,    0,  218,  219,  218,  221,
      222,    0,  221,  222,    0,    0,  221,  222,  221,  224,
      224,  224,  224,  224,  224,  224,  224,  225,    0,  225,
      225,    0,  225,  225,  226,  226,  226,  226,  228,    0,

      228,  228,    0,  228,  228,  230,  230,  230,  230,  230,
      230,  231,  231,  233,  233,    0,  233,  233,  234,    0,
      234,  234,  235,  235,    0,  235,  235,  237,  237,  237,
      237,  237,  237,  239,  239,    0,  239,  239,  240,  240,
        0,  240,  240,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223
    } ;

/* Table of booleans, true if rule could match eol. */
static NFSv3yyconst flex_int32_t NFSv3yy_rule_can_match_eol[41] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 
    0,     };

extern int NFSv3yy_flex_debug;
int NFSv3yy_flex_debug = 0;

static NFSv3yy_state_type *NFSv3yy_state_buf=0, *NFSv3yy_state_ptr=0;
static char *NFSv3yy_full_match;
static int NFSv3yy_lp;
#define REJECT \
{ \
*NFSv3yy_cp = (NFSv3yy_hold_char); /* undo effects of setting up NFSv3yytext */ \
NFSv3yy_cp = (NFSv3yy_full_match); /* restore poss. backed-over text */ \
++(NFSv3yy_lp); \
goto find_rule; \
}

static int NFSv3yy_more_offset = 0;
static int NFSv3yy_prev_more_offset = 0;
#define NFSv3yymore() ((NFSv3yy_more_offset) = NFSv3yy_flex_strlen( NFSv3yytext ))
#define YY_NEED_STRLEN
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET \
	{ \
	(NFSv3yy_more_offset) = (NFSv3yy_prev_more_offset); \
	NFSv3yyleng -= (NFSv3yy_more_offset); \
	}
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char NFSv3yytext[YYLMAX];
char *NFSv3yytext_ptr;
#line 1 "util/parser/lexer.l"
/*** WARNING - COMMENTS IN LEX MUST BE TAB INDENTED ***/
/* DEFINITIONS SECTION */
/* Everything between %{ ... %} is copied verbatim to the start of the lex generated C code. */
#line 7 "util/parser/lexer.l"
#include <string.h>
#include "cmpidt.h"
#include "parser.h"
/* #ifndef YY_FLEX_LEX_COMPAT
int NFSv3yylineno = 1;
#endif */

char * NFSv3comments = NULL;		/* String buffer to accumulate comments */
/* Some useful regular expressions to use in the RULES section */
/* Use the default NFSv3yywrap() behavior */
/* END OF DEFINITIONS SECTION */
#line 809 "<stdout>"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int NFSv3yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int NFSv3yylex_destroy (void );

int NFSv3yyget_debug (void );

void NFSv3yyset_debug (int debug_flag  );

YY_EXTRA_TYPE NFSv3yyget_extra (void );

void NFSv3yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *NFSv3yyget_in (void );

void NFSv3yyset_in  (FILE * in_str  );

FILE *NFSv3yyget_out (void );

void NFSv3yyset_out  (FILE * out_str  );

int NFSv3yyget_leng (void );

char *NFSv3yyget_text (void );

int NFSv3yyget_lineno (void );

void NFSv3yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int NFSv3yywrap (void );
#else
extern int NFSv3yywrap (void );
#endif
#endif

    static void NFSv3yyunput (int c,char *buf_ptr  );
    
#ifndef NFSv3yytext_ptr
static void NFSv3yy_flex_strncpy (char *,NFSv3yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int NFSv3yy_flex_strlen (NFSv3yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int NFSv3yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( NFSv3yytext, NFSv3yyleng, 1, NFSv3yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->NFSv3yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( NFSv3yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( NFSv3yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, NFSv3yyin))==0 && ferror(NFSv3yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(NFSv3yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "NFSv3yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef NFSv3yyterminate
#define NFSv3yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) NFSv3yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int NFSv3yylex (void);

#define YY_DECL int NFSv3yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after NFSv3yytext and NFSv3yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register NFSv3yy_state_type NFSv3yy_current_state;
	register char *NFSv3yy_cp, *NFSv3yy_bp;
	register int NFSv3yy_act;
    
#line 39 "util/parser/lexer.l"

	/* RULES SECTION */
	/* DESCRIBE EVERY LEXICAL TOKEN/PATTERN FOLLOWED BY THE APPROPRIATE ACTION.
	   TYPICALLY THE ACTION RETURNS THE TOKEN IDENTIFIER AND ITS VALUE (IN YYLVAL) */

	/* The following simple lexical tokens only return the token identifier */

#line 999 "<stdout>"

	if ( !(NFSv3yy_init) )
		{
		(NFSv3yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (NFSv3yy_state_buf) )
            (NFSv3yy_state_buf) = (NFSv3yy_state_type *)NFSv3yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (NFSv3yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in NFSv3yylex()" );

		if ( ! (NFSv3yy_start) )
			(NFSv3yy_start) = 1;	/* first start state */

		if ( ! NFSv3yyin )
			NFSv3yyin = stdin;

		if ( ! NFSv3yyout )
			NFSv3yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			NFSv3yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				NFSv3yy_create_buffer(NFSv3yyin,YY_BUF_SIZE );
		}

		NFSv3yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		NFSv3yy_cp = (NFSv3yy_c_buf_p);

		/* Support of NFSv3yytext. */
		*NFSv3yy_cp = (NFSv3yy_hold_char);

		/* NFSv3yy_bp points to the position in NFSv3yy_ch_buf of the start of
		 * the current run.
		 */
		NFSv3yy_bp = NFSv3yy_cp;

		NFSv3yy_current_state = (NFSv3yy_start);

		(NFSv3yy_state_ptr) = (NFSv3yy_state_buf);
		*(NFSv3yy_state_ptr)++ = NFSv3yy_current_state;

NFSv3yy_match:
		do
			{
			register YY_CHAR NFSv3yy_c = NFSv3yy_ec[YY_SC_TO_UI(*NFSv3yy_cp)];
			while ( NFSv3yy_chk[NFSv3yy_base[NFSv3yy_current_state] + NFSv3yy_c] != NFSv3yy_current_state )
				{
				NFSv3yy_current_state = (int) NFSv3yy_def[NFSv3yy_current_state];
				if ( NFSv3yy_current_state >= 224 )
					NFSv3yy_c = NFSv3yy_meta[(unsigned int) NFSv3yy_c];
				}
			NFSv3yy_current_state = NFSv3yy_nxt[NFSv3yy_base[NFSv3yy_current_state] + (unsigned int) NFSv3yy_c];
			*(NFSv3yy_state_ptr)++ = NFSv3yy_current_state;
			++NFSv3yy_cp;
			}
		while ( NFSv3yy_base[NFSv3yy_current_state] != 844 );

NFSv3yy_find_action:
		NFSv3yy_current_state = *--(NFSv3yy_state_ptr);
		(NFSv3yy_lp) = NFSv3yy_accept[NFSv3yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (NFSv3yy_lp) && (NFSv3yy_lp) < NFSv3yy_accept[NFSv3yy_current_state + 1] )
				{
				NFSv3yy_act = NFSv3yy_acclist[(NFSv3yy_lp)];
					{
					(NFSv3yy_full_match) = NFSv3yy_cp;
					break;
					}
				}
			--NFSv3yy_cp;
			NFSv3yy_current_state = *--(NFSv3yy_state_ptr);
			(NFSv3yy_lp) = NFSv3yy_accept[NFSv3yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( NFSv3yy_act != YY_END_OF_BUFFER && NFSv3yy_rule_can_match_eol[NFSv3yy_act] )
			{
			int NFSv3yyl;
			for ( NFSv3yyl = (NFSv3yy_prev_more_offset); NFSv3yyl < NFSv3yyleng; ++NFSv3yyl )
				if ( NFSv3yytext[NFSv3yyl] == '\n' )
					   
    NFSv3yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( NFSv3yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 46 "util/parser/lexer.l"
{
	return(ANONGID);
	}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 50 "util/parser/lexer.l"
{
	return(ANONUID);
	}
	YY_BREAK
/* The following lexical tokens return the token identifier and the value of the token (in NFSv3yylval) */
case 3:
#line 57 "util/parser/lexer.l"
case 4:
YY_RULE_SETUP
#line 57 "util/parser/lexer.l"
{
	NFSv3yylval.string = (char *)strdup(NFSv3yytext);
	return(SQUASH);
	}
	YY_BREAK
case 5:
#line 63 "util/parser/lexer.l"
case 6:
YY_RULE_SETUP
#line 63 "util/parser/lexer.l"
{
	NFSv3yylval.string = (char *)strdup(NFSv3yytext);
	return(PERMISSION);
	}
	YY_BREAK
case 7:
#line 69 "util/parser/lexer.l"
case 8:
YY_RULE_SETUP
#line 69 "util/parser/lexer.l"
{
	NFSv3yylval.boolean = !strcmp(NFSv3yytext,"secure");
	return(SECURE);
	}
	YY_BREAK
case 9:
#line 75 "util/parser/lexer.l"
case 10:
YY_RULE_SETUP
#line 75 "util/parser/lexer.l"
{
	NFSv3yylval.boolean = !strcmp(NFSv3yytext,"sync");
	return(SYNC);
	}
	YY_BREAK
case 11:
#line 81 "util/parser/lexer.l"
case 12:
YY_RULE_SETUP
#line 81 "util/parser/lexer.l"
{
	NFSv3yylval.boolean = !strcmp(NFSv3yytext,"wdelay");
	return(WRITEDELAY);
	}
	YY_BREAK
case 13:
#line 87 "util/parser/lexer.l"
case 14:
YY_RULE_SETUP
#line 87 "util/parser/lexer.l"
{
	NFSv3yylval.boolean = !strcmp(NFSv3yytext,"hide");
	return(HIDE);
	}
	YY_BREAK
case 15:
#line 93 "util/parser/lexer.l"
case 16:
YY_RULE_SETUP
#line 93 "util/parser/lexer.l"
{
	NFSv3yylval.boolean = !strcmp(NFSv3yytext,"crossmnt");
	return(CROSSMNT);
	}
	YY_BREAK
case 17:
#line 99 "util/parser/lexer.l"
case 18:
YY_RULE_SETUP
#line 99 "util/parser/lexer.l"
{
	NFSv3yylval.string = (char *)strdup(NFSv3yytext);
	return(ALLSQUASH);
	}
	YY_BREAK
case 19:
#line 105 "util/parser/lexer.l"
case 20:
YY_RULE_SETUP
#line 105 "util/parser/lexer.l"
{
	NFSv3yylval.boolean = !strcmp(NFSv3yytext,"acl");
	return(ACL);
	}
	YY_BREAK
case 21:
#line 111 "util/parser/lexer.l"
case 22:
YY_RULE_SETUP
#line 111 "util/parser/lexer.l"
{
	NFSv3yylval.boolean = !strcmp(NFSv3yytext,"subtree_check");
	return(SUBTREECHECK);
	}
	YY_BREAK
case 23:
#line 117 "util/parser/lexer.l"
case 24:
#line 118 "util/parser/lexer.l"
case 25:
#line 119 "util/parser/lexer.l"
case 26:
YY_RULE_SETUP
#line 119 "util/parser/lexer.l"
{
	NFSv3yylval.boolean = !strcmp(NFSv3yytext,"secure_locks") || !strcmp(NFSv3yytext,"auth_nlm");
	return(SECURELOCKS);
	}
	YY_BREAK
/* Absolute pathname of the exported Unix directory */
case 27:
YY_RULE_SETUP
#line 125 "util/parser/lexer.l"
{
	NFSv3yylval.string = (char *)strdup(NFSv3yytext);
	return(PATHNAME);
	}
	YY_BREAK
/* Different ways to specify the NFS client machine name(s) */
case 28:
#line 132 "util/parser/lexer.l"
case 29:
#line 133 "util/parser/lexer.l"
case 30:
#line 134 "util/parser/lexer.l"
case 31:
#line 135 "util/parser/lexer.l"
case 32:
#line 136 "util/parser/lexer.l"
case 33:
YY_RULE_SETUP
#line 136 "util/parser/lexer.l"
{
	NFSv3yylval.string = (char *)strdup(NFSv3yytext);
	return(HOSTNAME);
	}
	YY_BREAK
/* UID or GID */
case 34:
YY_RULE_SETUP
#line 142 "util/parser/lexer.l"
{
	NFSv3yylval.uint16 = strtoul(NFSv3yytext,NULL,0);
	return(NUMBER);
	}
	YY_BREAK
case 35:
/* rule 35 can match eol */
YY_RULE_SETUP
#line 147 "util/parser/lexer.l"
{
	NFSv3yylineno++;
	}
	YY_BREAK
/* Ignore whitespace */
case 36:
YY_RULE_SETUP
#line 152 "util/parser/lexer.l"
;
	YY_BREAK
/* Ignore end-of-line continuation markers */
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 155 "util/parser/lexer.l"
{
	NFSv3yylineno++;
	}
	YY_BREAK
/* Ignore comments */
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 160 "util/parser/lexer.l"
{
	/* Extend the comments buffer */
	if (NFSv3comments == NULL) {
    	   NFSv3comments = malloc(strlen(NFSv3yytext)+1);
	   strcpy(NFSv3comments,"");
	} else {
	   char * newcomments = malloc(strlen(NFSv3comments)+strlen(NFSv3yytext)+1);
	   strcpy(newcomments, NFSv3comments);
	   free(NFSv3comments);
	   NFSv3comments = newcomments;
	}

	/* Add this comment line to the comments buffer */
	strcat(NFSv3comments,NFSv3yytext);
	}
	YY_BREAK
/* Return single character punctuation characters as-is */
case 39:
YY_RULE_SETUP
#line 177 "util/parser/lexer.l"
{
	return(NFSv3yytext[0]);
	}
	YY_BREAK
/* END OF RULES SECTION */
case 40:
YY_RULE_SETUP
#line 182 "util/parser/lexer.l"
ECHO;
	YY_BREAK
#line 1325 "<stdout>"
			case YY_STATE_EOF(INITIAL):
				NFSv3yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int NFSv3yy_amount_of_matched_text = (int) (NFSv3yy_cp - (NFSv3yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*NFSv3yy_cp = (NFSv3yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->NFSv3yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed NFSv3yyin at a new source and called
			 * NFSv3yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(NFSv3yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->NFSv3yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->NFSv3yy_input_file = NFSv3yyin;
			YY_CURRENT_BUFFER_LVALUE->NFSv3yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for NFSv3yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since NFSv3yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (NFSv3yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->NFSv3yy_ch_buf[(NFSv3yy_n_chars)] )
			{ /* This was really a NUL. */
			NFSv3yy_state_type NFSv3yy_next_state;

			(NFSv3yy_c_buf_p) = (NFSv3yytext_ptr) + NFSv3yy_amount_of_matched_text;

			NFSv3yy_current_state = NFSv3yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * NFSv3yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			NFSv3yy_next_state = NFSv3yy_try_NUL_trans( NFSv3yy_current_state );

			NFSv3yy_bp = (NFSv3yytext_ptr) + YY_MORE_ADJ;

			if ( NFSv3yy_next_state )
				{
				/* Consume the NUL. */
				NFSv3yy_cp = ++(NFSv3yy_c_buf_p);
				NFSv3yy_current_state = NFSv3yy_next_state;
				goto NFSv3yy_match;
				}

			else
				{
				NFSv3yy_cp = (NFSv3yy_c_buf_p);
				goto NFSv3yy_find_action;
				}
			}

		else switch ( NFSv3yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(NFSv3yy_did_buffer_switch_on_eof) = 0;

				if ( NFSv3yywrap( ) )
					{
					/* Note: because we've taken care in
					 * NFSv3yy_get_next_buffer() to have set up
					 * NFSv3yytext, we can now set up
					 * NFSv3yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(NFSv3yy_c_buf_p) = (NFSv3yytext_ptr) + YY_MORE_ADJ;

					NFSv3yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (NFSv3yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(NFSv3yy_c_buf_p) =
					(NFSv3yytext_ptr) + NFSv3yy_amount_of_matched_text;

				NFSv3yy_current_state = NFSv3yy_get_previous_state(  );

				NFSv3yy_cp = (NFSv3yy_c_buf_p);
				NFSv3yy_bp = (NFSv3yytext_ptr) + YY_MORE_ADJ;
				goto NFSv3yy_match;

			case EOB_ACT_LAST_MATCH:
				(NFSv3yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->NFSv3yy_ch_buf[(NFSv3yy_n_chars)];

				NFSv3yy_current_state = NFSv3yy_get_previous_state(  );

				NFSv3yy_cp = (NFSv3yy_c_buf_p);
				NFSv3yy_bp = (NFSv3yytext_ptr) + YY_MORE_ADJ;
				goto NFSv3yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of NFSv3yylex */

/* NFSv3yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int NFSv3yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->NFSv3yy_ch_buf;
	register char *source = (NFSv3yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (NFSv3yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->NFSv3yy_ch_buf[(NFSv3yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->NFSv3yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (NFSv3yy_c_buf_p) - (NFSv3yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((NFSv3yy_c_buf_p) - (NFSv3yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->NFSv3yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->NFSv3yy_n_chars = (NFSv3yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->NFSv3yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->NFSv3yy_ch_buf[number_to_move]),
			(NFSv3yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->NFSv3yy_n_chars = (NFSv3yy_n_chars);
		}

	if ( (NFSv3yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			NFSv3yyrestart(NFSv3yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->NFSv3yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((NFSv3yy_size_t) ((NFSv3yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->NFSv3yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		NFSv3yy_size_t new_size = (NFSv3yy_n_chars) + number_to_move + ((NFSv3yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->NFSv3yy_ch_buf = (char *) NFSv3yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->NFSv3yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->NFSv3yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in NFSv3yy_get_next_buffer()" );
	}

	(NFSv3yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->NFSv3yy_ch_buf[(NFSv3yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->NFSv3yy_ch_buf[(NFSv3yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(NFSv3yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->NFSv3yy_ch_buf[0];

	return ret_val;
}

/* NFSv3yy_get_previous_state - get the state just before the EOB char was reached */

    static NFSv3yy_state_type NFSv3yy_get_previous_state (void)
{
	register NFSv3yy_state_type NFSv3yy_current_state;
	register char *NFSv3yy_cp;
    
	NFSv3yy_current_state = (NFSv3yy_start);

	(NFSv3yy_state_ptr) = (NFSv3yy_state_buf);
	*(NFSv3yy_state_ptr)++ = NFSv3yy_current_state;

	for ( NFSv3yy_cp = (NFSv3yytext_ptr) + YY_MORE_ADJ; NFSv3yy_cp < (NFSv3yy_c_buf_p); ++NFSv3yy_cp )
		{
		register YY_CHAR NFSv3yy_c = (*NFSv3yy_cp ? NFSv3yy_ec[YY_SC_TO_UI(*NFSv3yy_cp)] : 1);
		while ( NFSv3yy_chk[NFSv3yy_base[NFSv3yy_current_state] + NFSv3yy_c] != NFSv3yy_current_state )
			{
			NFSv3yy_current_state = (int) NFSv3yy_def[NFSv3yy_current_state];
			if ( NFSv3yy_current_state >= 224 )
				NFSv3yy_c = NFSv3yy_meta[(unsigned int) NFSv3yy_c];
			}
		NFSv3yy_current_state = NFSv3yy_nxt[NFSv3yy_base[NFSv3yy_current_state] + (unsigned int) NFSv3yy_c];
		*(NFSv3yy_state_ptr)++ = NFSv3yy_current_state;
		}

	return NFSv3yy_current_state;
}

/* NFSv3yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = NFSv3yy_try_NUL_trans( current_state );
 */
    static NFSv3yy_state_type NFSv3yy_try_NUL_trans  (NFSv3yy_state_type NFSv3yy_current_state )
{
	register int NFSv3yy_is_jam;
    
	register YY_CHAR NFSv3yy_c = 1;
	while ( NFSv3yy_chk[NFSv3yy_base[NFSv3yy_current_state] + NFSv3yy_c] != NFSv3yy_current_state )
		{
		NFSv3yy_current_state = (int) NFSv3yy_def[NFSv3yy_current_state];
		if ( NFSv3yy_current_state >= 224 )
			NFSv3yy_c = NFSv3yy_meta[(unsigned int) NFSv3yy_c];
		}
	NFSv3yy_current_state = NFSv3yy_nxt[NFSv3yy_base[NFSv3yy_current_state] + (unsigned int) NFSv3yy_c];
	NFSv3yy_is_jam = (NFSv3yy_current_state == 223);
	if ( ! NFSv3yy_is_jam )
		*(NFSv3yy_state_ptr)++ = NFSv3yy_current_state;

	return NFSv3yy_is_jam ? 0 : NFSv3yy_current_state;
}

    static void NFSv3yyunput (int c, register char * NFSv3yy_bp )
{
	register char *NFSv3yy_cp;
    
    NFSv3yy_cp = (NFSv3yy_c_buf_p);

	/* undo effects of setting up NFSv3yytext */
	*NFSv3yy_cp = (NFSv3yy_hold_char);

	if ( NFSv3yy_cp < YY_CURRENT_BUFFER_LVALUE->NFSv3yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (NFSv3yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->NFSv3yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->NFSv3yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->NFSv3yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->NFSv3yy_ch_buf )
			*--dest = *--source;

		NFSv3yy_cp += (int) (dest - source);
		NFSv3yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->NFSv3yy_n_chars =
			(NFSv3yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->NFSv3yy_buf_size;

		if ( NFSv3yy_cp < YY_CURRENT_BUFFER_LVALUE->NFSv3yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--NFSv3yy_cp = (char) c;

    if ( c == '\n' ){
        --NFSv3yylineno;
    }

	(NFSv3yytext_ptr) = NFSv3yy_bp;
	(NFSv3yy_hold_char) = *NFSv3yy_cp;
	(NFSv3yy_c_buf_p) = NFSv3yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int NFSv3yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(NFSv3yy_c_buf_p) = (NFSv3yy_hold_char);

	if ( *(NFSv3yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* NFSv3yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (NFSv3yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->NFSv3yy_ch_buf[(NFSv3yy_n_chars)] )
			/* This was really a NUL. */
			*(NFSv3yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (NFSv3yy_c_buf_p) - (NFSv3yytext_ptr);
			++(NFSv3yy_c_buf_p);

			switch ( NFSv3yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because NFSv3yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					NFSv3yyrestart(NFSv3yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( NFSv3yywrap( ) )
						return EOF;

					if ( ! (NFSv3yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return NFSv3yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(NFSv3yy_c_buf_p) = (NFSv3yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (NFSv3yy_c_buf_p);	/* cast for 8-bit char's */
	*(NFSv3yy_c_buf_p) = '\0';	/* preserve NFSv3yytext */
	(NFSv3yy_hold_char) = *++(NFSv3yy_c_buf_p);

	if ( c == '\n' )
		   
    NFSv3yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void NFSv3yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        NFSv3yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            NFSv3yy_create_buffer(NFSv3yyin,YY_BUF_SIZE );
	}

	NFSv3yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	NFSv3yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void NFSv3yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		NFSv3yypop_buffer_state();
	 *		NFSv3yypush_buffer_state(new_buffer);
     */
	NFSv3yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(NFSv3yy_c_buf_p) = (NFSv3yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->NFSv3yy_buf_pos = (NFSv3yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->NFSv3yy_n_chars = (NFSv3yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	NFSv3yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (NFSv3yywrap()) processing, but the only time this flag
	 * is looked at is after NFSv3yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(NFSv3yy_did_buffer_switch_on_eof) = 1;
}

static void NFSv3yy_load_buffer_state  (void)
{
    	(NFSv3yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->NFSv3yy_n_chars;
	(NFSv3yytext_ptr) = (NFSv3yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->NFSv3yy_buf_pos;
	NFSv3yyin = YY_CURRENT_BUFFER_LVALUE->NFSv3yy_input_file;
	(NFSv3yy_hold_char) = *(NFSv3yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE NFSv3yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) NFSv3yyalloc(sizeof( struct NFSv3yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in NFSv3yy_create_buffer()" );

	b->NFSv3yy_buf_size = size;

	/* NFSv3yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->NFSv3yy_ch_buf = (char *) NFSv3yyalloc(b->NFSv3yy_buf_size + 2  );
	if ( ! b->NFSv3yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in NFSv3yy_create_buffer()" );

	b->NFSv3yy_is_our_buffer = 1;

	NFSv3yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with NFSv3yy_create_buffer()
 * 
 */
    void NFSv3yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->NFSv3yy_is_our_buffer )
		NFSv3yyfree((void *) b->NFSv3yy_ch_buf  );

	NFSv3yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a NFSv3yyrestart() or at EOF.
 */
    static void NFSv3yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	NFSv3yy_flush_buffer(b );

	b->NFSv3yy_input_file = file;
	b->NFSv3yy_fill_buffer = 1;

    /* If b is the current buffer, then NFSv3yy_init_buffer was _probably_
     * called from NFSv3yyrestart() or through NFSv3yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->NFSv3yy_bs_lineno = 1;
        b->NFSv3yy_bs_column = 0;
    }

        b->NFSv3yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void NFSv3yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->NFSv3yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->NFSv3yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->NFSv3yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->NFSv3yy_buf_pos = &b->NFSv3yy_ch_buf[0];

	b->NFSv3yy_at_bol = 1;
	b->NFSv3yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		NFSv3yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void NFSv3yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	NFSv3yyensure_buffer_stack();

	/* This block is copied from NFSv3yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(NFSv3yy_c_buf_p) = (NFSv3yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->NFSv3yy_buf_pos = (NFSv3yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->NFSv3yy_n_chars = (NFSv3yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(NFSv3yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from NFSv3yy_switch_to_buffer. */
	NFSv3yy_load_buffer_state( );
	(NFSv3yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void NFSv3yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	NFSv3yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((NFSv3yy_buffer_stack_top) > 0)
		--(NFSv3yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		NFSv3yy_load_buffer_state( );
		(NFSv3yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void NFSv3yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(NFSv3yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(NFSv3yy_buffer_stack) = (struct NFSv3yy_buffer_state**)NFSv3yyalloc
								(num_to_alloc * sizeof(struct NFSv3yy_buffer_state*)
								);
		if ( ! (NFSv3yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in NFSv3yyensure_buffer_stack()" );
								  
		memset((NFSv3yy_buffer_stack), 0, num_to_alloc * sizeof(struct NFSv3yy_buffer_state*));
				
		(NFSv3yy_buffer_stack_max) = num_to_alloc;
		(NFSv3yy_buffer_stack_top) = 0;
		return;
	}

	if ((NFSv3yy_buffer_stack_top) >= ((NFSv3yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (NFSv3yy_buffer_stack_max) + grow_size;
		(NFSv3yy_buffer_stack) = (struct NFSv3yy_buffer_state**)NFSv3yyrealloc
								((NFSv3yy_buffer_stack),
								num_to_alloc * sizeof(struct NFSv3yy_buffer_state*)
								);
		if ( ! (NFSv3yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in NFSv3yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((NFSv3yy_buffer_stack) + (NFSv3yy_buffer_stack_max), 0, grow_size * sizeof(struct NFSv3yy_buffer_state*));
		(NFSv3yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE NFSv3yy_scan_buffer  (char * base, NFSv3yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) NFSv3yyalloc(sizeof( struct NFSv3yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in NFSv3yy_scan_buffer()" );

	b->NFSv3yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->NFSv3yy_buf_pos = b->NFSv3yy_ch_buf = base;
	b->NFSv3yy_is_our_buffer = 0;
	b->NFSv3yy_input_file = 0;
	b->NFSv3yy_n_chars = b->NFSv3yy_buf_size;
	b->NFSv3yy_is_interactive = 0;
	b->NFSv3yy_at_bol = 1;
	b->NFSv3yy_fill_buffer = 0;
	b->NFSv3yy_buffer_status = YY_BUFFER_NEW;

	NFSv3yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to NFSv3yylex() will
 * scan from a @e copy of @a str.
 * @param NFSv3yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       NFSv3yy_scan_bytes() instead.
 */
YY_BUFFER_STATE NFSv3yy_scan_string (NFSv3yyconst char * NFSv3yystr )
{
    
	return NFSv3yy_scan_bytes(NFSv3yystr,strlen(NFSv3yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to NFSv3yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE NFSv3yy_scan_bytes  (NFSv3yyconst char * NFSv3yybytes, int  _NFSv3yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	NFSv3yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _NFSv3yybytes_len + 2;
	buf = (char *) NFSv3yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in NFSv3yy_scan_bytes()" );

	for ( i = 0; i < _NFSv3yybytes_len; ++i )
		buf[i] = NFSv3yybytes[i];

	buf[_NFSv3yybytes_len] = buf[_NFSv3yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = NFSv3yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in NFSv3yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->NFSv3yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void NFSv3yy_fatal_error (NFSv3yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine NFSv3yyless() so it works in section 3 code. */

#undef NFSv3yyless
#define NFSv3yyless(n) \
	do \
		{ \
		/* Undo effects of setting up NFSv3yytext. */ \
        int NFSv3yyless_macro_arg = (n); \
        YY_LESS_LINENO(NFSv3yyless_macro_arg);\
		NFSv3yytext[NFSv3yyleng] = (NFSv3yy_hold_char); \
		(NFSv3yy_c_buf_p) = NFSv3yytext + NFSv3yyless_macro_arg; \
		(NFSv3yy_hold_char) = *(NFSv3yy_c_buf_p); \
		*(NFSv3yy_c_buf_p) = '\0'; \
		NFSv3yyleng = NFSv3yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int NFSv3yyget_lineno  (void)
{
        
    return NFSv3yylineno;
}

/** Get the input stream.
 * 
 */
FILE *NFSv3yyget_in  (void)
{
        return NFSv3yyin;
}

/** Get the output stream.
 * 
 */
FILE *NFSv3yyget_out  (void)
{
        return NFSv3yyout;
}

/** Get the length of the current token.
 * 
 */
int NFSv3yyget_leng  (void)
{
        return NFSv3yyleng;
}

/** Get the current token.
 * 
 */

char *NFSv3yyget_text  (void)
{
        return NFSv3yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void NFSv3yyset_lineno (int  line_number )
{
    
    NFSv3yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see NFSv3yy_switch_to_buffer
 */
void NFSv3yyset_in (FILE *  in_str )
{
        NFSv3yyin = in_str ;
}

void NFSv3yyset_out (FILE *  out_str )
{
        NFSv3yyout = out_str ;
}

int NFSv3yyget_debug  (void)
{
        return NFSv3yy_flex_debug;
}

void NFSv3yyset_debug (int  bdebug )
{
        NFSv3yy_flex_debug = bdebug ;
}

static int NFSv3yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from NFSv3yylex_destroy(), so don't allocate here.
     */

    /* We do not touch NFSv3yylineno unless the option is enabled. */
    NFSv3yylineno =  1;
    
    (NFSv3yy_buffer_stack) = 0;
    (NFSv3yy_buffer_stack_top) = 0;
    (NFSv3yy_buffer_stack_max) = 0;
    (NFSv3yy_c_buf_p) = (char *) 0;
    (NFSv3yy_init) = 0;
    (NFSv3yy_start) = 0;

    (NFSv3yy_state_buf) = 0;
    (NFSv3yy_state_ptr) = 0;
    (NFSv3yy_full_match) = 0;
    (NFSv3yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    NFSv3yyin = stdin;
    NFSv3yyout = stdout;
#else
    NFSv3yyin = (FILE *) 0;
    NFSv3yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * NFSv3yylex_init()
     */
    return 0;
}

/* NFSv3yylex_destroy is for both reentrant and non-reentrant scanners. */
int NFSv3yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		NFSv3yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		NFSv3yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	NFSv3yyfree((NFSv3yy_buffer_stack) );
	(NFSv3yy_buffer_stack) = NULL;

    NFSv3yyfree ( (NFSv3yy_state_buf) );
    (NFSv3yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * NFSv3yylex() is called, initialization will occur. */
    NFSv3yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef NFSv3yytext_ptr
static void NFSv3yy_flex_strncpy (char* s1, NFSv3yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int NFSv3yy_flex_strlen (NFSv3yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *NFSv3yyalloc (NFSv3yy_size_t  size )
{
	return (void *) malloc( size );
}

void *NFSv3yyrealloc  (void * ptr, NFSv3yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void NFSv3yyfree (void * ptr )
{
	free( (char *) ptr );	/* see NFSv3yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "NFSv3yytables"

#line 182 "util/parser/lexer.l"


	/* USER SUBROUTINE SECTION */
	/* Everything below is copied verbatim to the end of the lex generated C code. */

void NFSv3yyerror(char *errmsg)
{
   fprintf(stderr, "NFSv3 parser, line %d: %s at '%s'\n", NFSv3yylineno, errmsg, NFSv3yytext);
}


