
#line 3 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define NFSv3yyconst const
#else
#define NFSv3yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (NFSv3yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((NFSv3yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE NFSv3yyrestart(NFSv3yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(NFSv3yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct NFSv3yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int NFSv3yyleng;

extern FILE *NFSv3yyin, *NFSv3yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for NFSv3yy_rule_can_match_eol because it requires
     *       access to the local variable NFSv3yy_act. Since NFSv3yyless() is a macro, it would break
     *       existing scanners that call NFSv3yyless() from OUTSIDE NFSv3yylex. 
     *       One obvious solution it to make NFSv3yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-NFSv3yylineno scanner, because NFSv3yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int NFSv3yyl;\
                for ( NFSv3yyl = n; NFSv3yyl < NFSv3yyleng; ++NFSv3yyl )\
                    if ( NFSv3yytext[NFSv3yyl] == '\n' )\
                        --NFSv3yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define NFSv3yyless(n) \
	do \
		{ \
		/* Undo effects of setting up NFSv3yytext. */ \
        int NFSv3yyless_macro_arg = (n); \
        YY_LESS_LINENO(NFSv3yyless_macro_arg);\
		*NFSv3yy_cp = (NFSv3yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(NFSv3yy_c_buf_p) = NFSv3yy_cp = NFSv3yy_bp + NFSv3yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up NFSv3yytext again */ \
		} \
	while ( 0 )

#define unput(c) NFSv3yyunput( c, (NFSv3yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t NFSv3yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct NFSv3yy_buffer_state
	{
	FILE *NFSv3yy_input_file;

	char *NFSv3yy_ch_buf;		/* input buffer */
	char *NFSv3yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	NFSv3yy_size_t NFSv3yy_buf_size;

	/* Number of characters read into NFSv3yy_ch_buf, not including EOB
	 * characters.
	 */
	int NFSv3yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int NFSv3yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int NFSv3yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int NFSv3yy_at_bol;

    int NFSv3yy_bs_lineno; /**< The line count. */
    int NFSv3yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int NFSv3yy_fill_buffer;

	int NFSv3yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via NFSv3yyrestart()), so that the user can continue scanning by
	 * just pointing NFSv3yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t NFSv3yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t NFSv3yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * NFSv3yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (NFSv3yy_buffer_stack) \
                          ? (NFSv3yy_buffer_stack)[(NFSv3yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (NFSv3yy_buffer_stack)[(NFSv3yy_buffer_stack_top)]

/* NFSv3yy_hold_char holds the character lost when NFSv3yytext is formed. */
static char NFSv3yy_hold_char;
static int NFSv3yy_n_chars;		/* number of characters read into NFSv3yy_ch_buf */
int NFSv3yyleng;

/* Points to current character in buffer. */
static char *NFSv3yy_c_buf_p = (char *) 0;
static int NFSv3yy_init = 0;		/* whether we need to initialize */
static int NFSv3yy_start = 0;	/* start state number */

/* Flag which is used to allow NFSv3yywrap()'s to do buffer switches
 * instead of setting up a fresh NFSv3yyin.  A bit of a hack ...
 */
static int NFSv3yy_did_buffer_switch_on_eof;

void NFSv3yyrestart (FILE *input_file  );
void NFSv3yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE NFSv3yy_create_buffer (FILE *file,int size  );
void NFSv3yy_delete_buffer (YY_BUFFER_STATE b  );
void NFSv3yy_flush_buffer (YY_BUFFER_STATE b  );
void NFSv3yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void NFSv3yypop_buffer_state (void );

static void NFSv3yyensure_buffer_stack (void );
static void NFSv3yy_load_buffer_state (void );
static void NFSv3yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER NFSv3yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE NFSv3yy_scan_buffer (char *base,NFSv3yy_size_t size  );
YY_BUFFER_STATE NFSv3yy_scan_string (NFSv3yyconst char *NFSv3yy_str  );
YY_BUFFER_STATE NFSv3yy_scan_bytes (NFSv3yyconst char *bytes,int len  );

void *NFSv3yyalloc (NFSv3yy_size_t  );
void *NFSv3yyrealloc (void *,NFSv3yy_size_t  );
void NFSv3yyfree (void *  );

#define NFSv3yy_new_buffer NFSv3yy_create_buffer

#define NFSv3yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        NFSv3yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            NFSv3yy_create_buffer(NFSv3yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->NFSv3yy_is_interactive = is_interactive; \
	}

#define NFSv3yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        NFSv3yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            NFSv3yy_create_buffer(NFSv3yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->NFSv3yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->NFSv3yy_at_bol)

/* Begin user sect3 */

#define NFSv3yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *NFSv3yyin = (FILE *) 0, *NFSv3yyout = (FILE *) 0;

typedef int NFSv3yy_state_type;

#define YY_FLEX_LEX_COMPAT
extern int NFSv3yylineno;

int NFSv3yylineno = 1;

extern char NFSv3yytext[];

static NFSv3yy_state_type NFSv3yy_get_previous_state (void );
static NFSv3yy_state_type NFSv3yy_try_NUL_trans (NFSv3yy_state_type current_state  );
static int NFSv3yy_get_next_buffer (void );
static void NFSv3yy_fatal_error (NFSv3yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up NFSv3yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(NFSv3yytext_ptr) = NFSv3yy_bp; \
	NFSv3yyleng = (size_t) (NFSv3yy_cp - NFSv3yy_bp); \
	(NFSv3yy_hold_char) = *NFSv3yy_cp; \
	*NFSv3yy_cp = '\0'; \
	if ( NFSv3yyleng + (NFSv3yy_more_offset) >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	NFSv3yy_flex_strncpy( &NFSv3yytext[(NFSv3yy_more_offset)], (NFSv3yytext_ptr), NFSv3yyleng + 1 ); \
	NFSv3yyleng += (NFSv3yy_more_offset); \
	(NFSv3yy_prev_more_offset) = (NFSv3yy_more_offset); \
	(NFSv3yy_more_offset) = 0; \
	(NFSv3yy_c_buf_p) = NFSv3yy_cp;

#define YY_NUM_RULES 35
#define YY_END_OF_BUFFER 36
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct NFSv3yy_trans_info
	{
	flex_int32_t NFSv3yy_verify;
	flex_int32_t NFSv3yy_nxt;
	};
static NFSv3yyconst flex_int16_t NFSv3yy_acclist[229] =
    {   0,
       36,   34,   35,   31,   34,   35,   30,   35,   34,   35,
       24,   34,   35,   22,   34,   35,   29,   34,   35,   34,
       35,   34,   35,   23,   34,   35,   34,   35,   23,   34,
       35,   23,   34,   35,   23,   34,   35,   23,   34,   35,
       23,   34,   35,   23,   34,   35,   23,   34,   35,   31,
       33,   22,   29,   28,   23,   32,   23,   23,   23,   23,
       23,   23,   23,    7,   23,    6,   23,   23,   23,   23,
       23,   25,   22,   22,   28,   23,   25,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       25,   22,   23,   25,   23,   23,   23,   23,   14,   23,

       23,   23,   23,   23,   23,   23,   23,   23,   23,   10,
       23,   23,   25,   22,   23,   25,   23,   23,   23,   11,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   25,   23,   25,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   15,   23,   23,    8,   23,   23,
       12,   23,   26,   23,    1,   23,    2,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   18,   23,
        9,   23,   23,   23,   23,   23,   23,   23,   23,   27,
       23,   23,   23,   23,   23,   13,   23,   23,   23,   23,
        3,   23,   23,   23,   23,   23,   23,   23,   23,   23,

       20,   23,   23,   23,    5,   23,   23,   23,   23,   23,
       23,   19,   23,   23,   23,   23,   23,   16,   23,   21,
       23,    4,   23,   23,   27,   23,   17,   23
    } ;

static NFSv3yyconst flex_int16_t NFSv3yy_accept[196] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   11,   14,   17,
       20,   22,   24,   27,   29,   32,   35,   38,   41,   44,
       47,   50,   51,   51,   52,   52,   52,   53,   53,   53,
       54,   55,   56,   56,   57,   58,   59,   60,   61,   62,
       63,   64,   66,   68,   69,   70,   71,   72,   73,   74,
       75,   75,   76,   78,   79,   80,   81,   82,   83,   84,
       85,   86,   87,   88,   89,   90,   91,   92,   92,   93,
       93,   95,   95,   96,   97,   98,   99,  101,  102,  103,
      104,  105,  106,  107,  108,  109,  110,  112,  113,  114,
      115,  115,  117,  118,  119,  120,  122,  123,  124,  125,

      126,  127,  128,  129,  130,  131,  132,  133,  134,  134,
      136,  137,  138,  139,  140,  141,  142,  143,  144,  145,
      147,  148,  150,  151,  153,  154,  155,  157,  159,  160,
      161,  162,  163,  164,  165,  166,  167,  168,  168,  169,
      171,  173,  174,  175,  176,  177,  178,  179,  180,  181,
      182,  183,  184,  185,  186,  188,  189,  190,  191,  191,
      193,  194,  195,  196,  197,  198,  199,  200,  200,  201,
      203,  204,  205,  207,  208,  209,  209,  210,  211,  212,
      214,  215,  215,  216,  217,  218,  220,  220,  222,  224,
      225,  226,  227,  229,  229

    } ;

static NFSv3yyconst flex_int32_t NFSv3yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    1,    1,    1,    1,    1,
        1,    5,    6,    1,    7,    8,    9,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,    1,    1,    1,
        1,    1,   11,   12,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
        1,   14,    1,    1,   15,    1,   16,   17,   18,   19,

       20,   13,   21,   22,   23,   13,   24,   25,   26,   27,
       28,   13,   29,   30,   31,   32,   33,   13,   34,   13,
       35,   13,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static NFSv3yyconst flex_int32_t NFSv3yy_meta[36] =
    {   0,
        1,    1,    1,    1,    2,    3,    4,    5,    6,    7,
        2,    1,    8,    1,    4,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8
    } ;

static NFSv3yyconst flex_int16_t NFSv3yy_base[212] =
    {   0,
        0,    0,  298,  743,  290,  743,  285,  276,  274,   28,
      272,    0,   32,  276,   39,   34,   41,   43,   48,   78,
       50,  270,  260,  743,  254,    0,  243,  236,  230,   52,
        0,   69,    0,  743,   70,   79,   59,   68,   77,   71,
       94,   95,   85,   99,  104,  111,  115,  228,  226,    0,
       55,    0,  223,  121,  120,  125,  129,  137,  141,  161,
      145,  151,  155,  165,  169,  181,  203,    0,  190,  183,
      174,    0,  187,  188,  192,  204,  193,  197,  209,  213,
      214,  231,  234,  223,  235,  241,  240,  261,  171,  164,
      159,  158,  258,  262,  266,  270,  280,  284,  288,  294,

      308,  291,  298,  314,  315,  318,  319,  155,  149,  135,
      322,  339,  342,  343,  336,  359,  350,  364,  368,  367,
      375,  391,  385,  392,  116,  397,  396,  401,  402,  413,
      423,  424,  420,  429,  432,  441,  448,  132,  440,  449,
      457,  458,  466,  467,  474,  488,  478,  485,  195,  492,
      497,  504,  511,  508,  514,  522,  515,  532,  123,  525,
      531,  536,  541,  548,  553,  558,  552,  249,  559,  564,
      580,  583,  569,  575,  587,  112,  597,  592,  604,  608,
      609,  302,  614,  618,  615,  626,   98,  632,  635,  636,
       89,  640,  643,  743,  678,  685,  689,   85,  696,   77,

      702,  704,   65,  709,  713,  718,   59,  724,   33,  729,
      734
    } ;

static NFSv3yyconst flex_int16_t NFSv3yy_def[212] =
    {   0,
      194,    1,  194,  194,  194,  194,  195,  196,  197,  194,
      196,  198,  199,  194,  199,  199,  199,  199,  199,  199,
      199,  194,  195,  194,  196,  200,  201,  197,  194,  194,
      202,  199,  203,  194,  199,  199,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,  204,  201,  205,
      194,  202,  206,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,  204,  207,  208,  194,
      206,  209,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,  210,  208,
      194,  211,   20,   20,   20,   20,   20,   20,   20,   20,

       20,   20,   20,   20,   20,   20,   20,  210,  194,  211,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,  194,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,  194,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,  194,   20,
       20,   20,   20,   20,   20,   20,   20,   20,  194,   20,
       20,   20,   20,   20,   20,   20,   20,  194,   20,   20,
       20,   20,   20,   20,   20,  194,   20,   20,   20,   20,
       20,  194,   20,   20,   20,   20,  194,   20,   20,   20,
      194,   20,   20,    0,  194,  194,  194,  194,  194,  194,

      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194
    } ;

static NFSv3yyconst flex_int16_t NFSv3yy_nxt[779] =
    {   0,
        4,    5,    6,    7,    8,    4,    4,    4,    9,   10,
       11,   12,   13,   14,    4,   15,   13,   13,   13,   13,
       13,   16,   17,   13,   13,   13,   18,   13,   13,   19,
       20,   13,   13,   21,   13,   29,   25,   30,   25,   33,
       92,   33,   25,   25,   25,   25,   33,   25,   33,   25,
       33,   25,   25,   25,   25,   33,   39,   33,   25,   29,
       25,   30,   70,   35,   51,   36,   89,   40,   47,   37,
       41,   38,   53,   25,   25,   42,   33,   33,   32,   25,
       25,   43,   25,   25,   48,   33,   33,   32,   25,   25,
       32,   32,   31,   56,   54,   58,   32,   44,  191,   57,

       32,   59,   32,   32,   32,   32,   55,  191,   60,   32,
       45,   32,   46,   32,   32,   61,   63,   32,   32,   32,
       64,  182,   62,   32,  138,  125,   32,   32,   32,   32,
       32,   32,  168,   32,   66,   73,   32,   65,   32,   32,
       32,  149,   72,   32,   32,   32,   74,   32,   32,   32,
       76,   75,   32,   32,   32,   32,   77,   32,  125,   32,
       78,   32,   68,   32,   32,   72,  109,   83,   91,   32,
       32,   32,   50,   32,   32,   32,   79,   32,   68,   32,
       32,   72,   84,   32,   32,   32,   87,   85,   32,   32,
       80,   81,   91,   32,   82,   32,   86,   32,   50,   32,

       32,   32,  159,   32,  149,   88,   32,   32,   94,   96,
       68,   32,   32,   32,   98,   32,   32,   93,   97,   32,
       95,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       72,   32,   32,   32,   50,   68,   32,  104,   32,   51,
      100,   99,   32,   32,  194,   32,  101,   32,   32,  102,
       32,   50,  103,   32,   32,   32,  176,   32,  168,   32,
       32,   26,   24,   32,  105,   32,   32,   32,   32,   32,
      106,   22,   32,   32,   32,   32,  107,   32,   34,   26,
       32,   32,   28,   26,  112,   32,  111,   24,  113,   32,
       32,   22,   32,   32,   32,   32,   32,  194,   32,   32,

       32,  194,   32,   32,   32,  194,  114,   32,  194,  187,
      119,  182,   32,   32,   32,  194,  115,  120,   32,  116,
       32,  117,   32,   32,  118,   32,   32,   32,   32,  194,
       32,  194,   32,   32,  122,  194,  194,  123,   32,  194,
       32,   32,   32,  194,  121,  194,   32,   32,   32,   32,
       32,   32,   32,  124,  126,   32,   32,  127,   32,  194,
      128,   32,   32,  194,  194,  130,  194,  129,   32,   32,
       32,   32,  194,   32,   32,   32,   32,   32,   32,  194,
      131,  132,   32,   32,   32,  194,   32,   32,  194,  194,
      194,   32,  134,   32,   32,  133,   32,  194,   32,   32,

       32,   32,   32,  135,  137,  136,  194,   32,  194,   32,
       32,   32,  139,  194,  194,   32,   32,   32,  194,   32,
       32,   32,  194,   32,   32,   32,   32,  140,   32,   32,
       32,   32,  141,   32,   32,   32,   32,  142,  143,   32,
      194,  194,   32,   32,  145,   32,  194,   32,   32,  144,
      194,   32,   32,  194,   32,   32,   32,   32,   32,   32,
       32,   32,  148,   32,  146,  147,   32,   32,   32,  194,
      150,  151,   32,   32,   32,   32,   32,   32,  194,  194,
       32,   32,   32,   32,  152,   32,  154,  194,  194,   32,
       32,   32,   32,   32,  194,  194,  153,   32,   32,   32,

       32,   32,  158,  156,   32,  157,   32,   32,  155,  194,
       32,   32,   32,  160,  194,  194,   32,   32,  194,   32,
       32,  161,   32,   32,   32,  194,   32,  164,  162,   32,
       32,   32,  166,   32,   32,  194,   32,  194,   32,  163,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,  165,  167,   32,   32,   32,   32,  169,   32,
       32,  170,  172,   32,   32,   32,   32,   32,   32,  194,
       32,  175,   32,  171,  173,   32,  177,   32,   32,  194,
       32,  174,   32,   32,   32,   32,   32,   32,   32,  194,
       32,   32,   32,   32,   32,  178,   32,  194,   32,   32,

      179,   32,   32,   32,  181,  180,   32,   32,  194,   32,
      194,   32,   32,  194,   32,   32,   32,   32,  194,   32,
      183,   32,  184,   32,   32,  185,   32,   32,   32,   32,
      194,   32,  186,   32,  190,  194,   32,   32,   32,  189,
       32,   32,   32,   32,  188,   32,   32,   32,   32,   32,
       32,   32,   32,  192,   32,   32,  194,  194,   32,   32,
       32,  194,   32,  193,   32,  194,   32,   32,   32,   32,
       32,  194,   32,  194,   32,   32,  194,   32,   23,   23,
       23,   23,   23,   23,   23,   23,   25,  194,   25,   25,
      194,   25,   25,   27,   27,   27,   27,   32,  194,   32,

       32,  194,   32,   32,   49,   49,   49,   49,   49,   49,
       52,   52,   67,   67,  194,   67,   67,   69,  194,   69,
       69,   71,   71,  194,   71,   71,   90,   90,   90,   90,
       90,   90,  108,  108,  194,  108,  108,  110,  110,  194,
      110,  110,    3,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194
    } ;

static NFSv3yyconst flex_int16_t NFSv3yy_chk[779] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   10,   13,   10,   16,   13,
      209,   16,   13,   15,   16,   17,   15,   18,   17,   15,
       18,   17,   19,   18,   21,   19,   16,   21,   19,   30,
       21,   30,   51,   15,   51,   15,  207,   17,   21,   15,
       18,   15,  203,   32,   35,   19,   32,   35,   37,   32,
       35,   19,   20,   36,  200,   20,   36,   38,   20,   36,
       40,   37,  198,   37,   35,   39,   39,   20,  191,   38,

       38,   40,   38,   40,   43,   40,   36,  187,   41,   39,
       20,   39,   20,   41,   42,   41,   44,   43,   44,   43,
       45,  176,   42,   45,  125,  125,   41,   42,   41,   42,
       46,   44,  159,   44,   47,   54,   45,   46,   45,   55,
       54,  138,  110,   46,   56,   46,   55,   47,   57,   47,
       57,   56,   55,   54,   55,   54,   58,   56,  109,   56,
       59,   57,  108,   57,   61,   92,   91,   61,   91,   58,
       62,   58,   90,   59,   63,   59,   60,   61,   89,   61,
       60,   71,   62,   62,   64,   62,   65,   63,   65,   63,
       60,   60,   70,   60,   60,   60,   64,   64,   69,   64,

       66,   65,  149,   65,  149,   66,   73,   74,   74,   75,
       67,   75,   77,   66,   78,   66,   78,   73,   76,   73,
       74,   73,   74,   76,   75,   77,   75,   77,   79,   78,
       53,   78,   80,   81,   49,   48,   76,   84,   76,   29,
       80,   79,   84,   79,   28,   80,   81,   80,   81,   82,
       82,   27,   83,   83,   85,   84,  168,   84,  168,   87,
       86,   25,   23,   82,   85,   82,   83,   85,   83,   85,
       86,   22,   87,   86,   87,   86,   88,   93,   14,   11,
       88,   94,    9,    8,   94,   95,   93,    7,   95,   96,
       93,    5,   93,   88,   94,   88,   94,    3,   95,   97,

       95,    0,   96,   98,   96,    0,   97,   99,    0,  182,
      102,  182,   97,  100,   97,    0,   98,  103,   98,   99,
       99,  100,   99,  102,  101,  102,  100,  101,  100,    0,
      103,    0,  103,  104,  105,    0,    0,  106,  107,    0,
      101,  111,  101,    0,  104,    0,  104,  105,  104,  105,
      106,  107,  106,  107,  111,  115,  111,  112,  112,    0,
      113,  113,  114,    0,    0,  115,    0,  114,  115,  117,
      115,  112,    0,  112,  113,  114,  113,  114,  116,    0,
      116,  117,  117,  118,  117,    0,  120,  119,    0,    0,
        0,  116,  119,  116,  121,  118,  118,    0,  118,  120,

      119,  120,  119,  121,  123,  122,    0,  121,    0,  121,
      122,  124,  126,    0,    0,  127,  126,  123,    0,  123,
      128,  129,    0,  122,  124,  122,  124,  129,  127,  126,
      127,  126,  130,  128,  129,  128,  129,  131,  132,  133,
        0,    0,  131,  132,  134,  130,    0,  130,  134,  133,
        0,  135,  133,    0,  133,  131,  132,  131,  132,  139,
      136,  134,  137,  134,  135,  136,  135,  137,  140,    0,
      139,  141,  139,  136,  139,  136,  141,  142,    0,    0,
      137,  140,  137,  140,  142,  143,  144,    0,    0,  141,
      142,  141,  142,  145,    0,    0,  143,  147,  143,  144,

      143,  144,  148,  146,  148,  147,  145,  146,  145,    0,
      147,  150,  147,  150,    0,    0,  151,  148,    0,  148,
      146,  151,  146,  152,  150,    0,  150,  154,  152,  151,
      153,  151,  157,  155,  157,    0,  152,    0,  152,  153,
      154,  156,  154,  153,  160,  153,  155,  157,  155,  157,
      161,  158,  156,  158,  156,  162,  156,  160,  161,  160,
      163,  162,  164,  161,  158,  161,  158,  164,  162,    0,
      162,  167,  165,  163,  165,  163,  169,  166,  169,    0,
      164,  166,  164,  170,  167,  165,  167,  165,  173,    0,
      166,  169,  166,  169,  174,  171,  170,    0,  170,  171,

      172,  173,  172,  173,  175,  174,  175,  174,    0,  174,
        0,  178,  171,    0,  171,  172,  177,  172,    0,  175,
      177,  175,  178,  179,  178,  179,  178,  180,  181,  177,
        0,  177,  181,  183,  185,    0,  179,  184,  179,  184,
      180,  181,  180,  181,  183,  186,  183,  185,  183,  185,
      184,  188,  184,  190,  189,  190,    0,    0,  186,  192,
      186,    0,  193,  192,  188,    0,  188,  189,  190,  189,
      190,    0,  192,    0,  192,  193,    0,  193,  195,  195,
      195,  195,  195,  195,  195,  195,  196,    0,  196,  196,
        0,  196,  196,  197,  197,  197,  197,  199,    0,  199,

      199,    0,  199,  199,  201,  201,  201,  201,  201,  201,
      202,  202,  204,  204,    0,  204,  204,  205,    0,  205,
      205,  206,  206,    0,  206,  206,  208,  208,  208,  208,
      208,  208,  210,  210,    0,  210,  210,  211,  211,    0,
      211,  211,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194
    } ;

/* Table of booleans, true if rule could match eol. */
static NFSv3yyconst flex_int32_t NFSv3yy_rule_can_match_eol[36] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,     };

extern int NFSv3yy_flex_debug;
int NFSv3yy_flex_debug = 0;

static NFSv3yy_state_type *NFSv3yy_state_buf=0, *NFSv3yy_state_ptr=0;
static char *NFSv3yy_full_match;
static int NFSv3yy_lp;
#define REJECT \
{ \
*NFSv3yy_cp = (NFSv3yy_hold_char); /* undo effects of setting up NFSv3yytext */ \
NFSv3yy_cp = (NFSv3yy_full_match); /* restore poss. backed-over text */ \
++(NFSv3yy_lp); \
goto find_rule; \
}

static int NFSv3yy_more_offset = 0;
static int NFSv3yy_prev_more_offset = 0;
#define NFSv3yymore() ((NFSv3yy_more_offset) = NFSv3yy_flex_strlen( NFSv3yytext ))
#define YY_NEED_STRLEN
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET \
	{ \
	(NFSv3yy_more_offset) = (NFSv3yy_prev_more_offset); \
	NFSv3yyleng -= (NFSv3yy_more_offset); \
	}
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char NFSv3yytext[YYLMAX];
char *NFSv3yytext_ptr;
#line 1 "util/parser/lexer.l"
/*** WARNING - COMMENTS IN LEX MUST BE TAB INDENTED ***/
/* DEFINITIONS SECTION */
/* Everything between %{ ... %} is copied verbatim to the start of the lex generated C code. */
#line 7 "util/parser/lexer.l"
#include <string.h>
#include "cmpidt.h"
#include "parser.h"
#ifndef YY_FLEX_LEX_COMPAT
int NFSv3yylineno = 1;
#endif

char * NFSv3comments = NULL;		/* String buffer to accumulate comments */
/* Some useful regular expressions to use in the RULES section */
/* Use the default NFSv3yywrap() behavior */
/* END OF DEFINITIONS SECTION */
#line 775 "<stdout>"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int NFSv3yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int NFSv3yylex_destroy (void );

int NFSv3yyget_debug (void );

void NFSv3yyset_debug (int debug_flag  );

YY_EXTRA_TYPE NFSv3yyget_extra (void );

void NFSv3yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *NFSv3yyget_in (void );

void NFSv3yyset_in  (FILE * in_str  );

FILE *NFSv3yyget_out (void );

void NFSv3yyset_out  (FILE * out_str  );

int NFSv3yyget_leng (void );

char *NFSv3yyget_text (void );

int NFSv3yyget_lineno (void );

void NFSv3yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int NFSv3yywrap (void );
#else
extern int NFSv3yywrap (void );
#endif
#endif

    static void NFSv3yyunput (int c,char *buf_ptr  );
    
#ifndef NFSv3yytext_ptr
static void NFSv3yy_flex_strncpy (char *,NFSv3yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int NFSv3yy_flex_strlen (NFSv3yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int NFSv3yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( NFSv3yytext, NFSv3yyleng, 1, NFSv3yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->NFSv3yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( NFSv3yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( NFSv3yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, NFSv3yyin))==0 && ferror(NFSv3yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(NFSv3yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "NFSv3yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef NFSv3yyterminate
#define NFSv3yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) NFSv3yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int NFSv3yylex (void);

#define YY_DECL int NFSv3yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after NFSv3yytext and NFSv3yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register NFSv3yy_state_type NFSv3yy_current_state;
	register char *NFSv3yy_cp, *NFSv3yy_bp;
	register int NFSv3yy_act;
    
#line 39 "util/parser/lexer.l"

	/* RULES SECTION */
	/* DESCRIBE EVERY LEXICAL TOKEN/PATTERN FOLLOWED BY THE APPROPRIATE ACTION.
	   TYPICALLY THE ACTION RETURNS THE TOKEN IDENTIFIER AND ITS VALUE (IN YYLVAL) */

	/* The following simple lexical tokens only return the token identifier */

#line 965 "<stdout>"

	if ( !(NFSv3yy_init) )
		{
		(NFSv3yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (NFSv3yy_state_buf) )
            (NFSv3yy_state_buf) = (NFSv3yy_state_type *)NFSv3yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (NFSv3yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in NFSv3yylex()" );

		if ( ! (NFSv3yy_start) )
			(NFSv3yy_start) = 1;	/* first start state */

		if ( ! NFSv3yyin )
			NFSv3yyin = stdin;

		if ( ! NFSv3yyout )
			NFSv3yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			NFSv3yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				NFSv3yy_create_buffer(NFSv3yyin,YY_BUF_SIZE );
		}

		NFSv3yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		NFSv3yy_cp = (NFSv3yy_c_buf_p);

		/* Support of NFSv3yytext. */
		*NFSv3yy_cp = (NFSv3yy_hold_char);

		/* NFSv3yy_bp points to the position in NFSv3yy_ch_buf of the start of
		 * the current run.
		 */
		NFSv3yy_bp = NFSv3yy_cp;

		NFSv3yy_current_state = (NFSv3yy_start);

		(NFSv3yy_state_ptr) = (NFSv3yy_state_buf);
		*(NFSv3yy_state_ptr)++ = NFSv3yy_current_state;

NFSv3yy_match:
		do
			{
			register YY_CHAR NFSv3yy_c = NFSv3yy_ec[YY_SC_TO_UI(*NFSv3yy_cp)];
			while ( NFSv3yy_chk[NFSv3yy_base[NFSv3yy_current_state] + NFSv3yy_c] != NFSv3yy_current_state )
				{
				NFSv3yy_current_state = (int) NFSv3yy_def[NFSv3yy_current_state];
				if ( NFSv3yy_current_state >= 195 )
					NFSv3yy_c = NFSv3yy_meta[(unsigned int) NFSv3yy_c];
				}
			NFSv3yy_current_state = NFSv3yy_nxt[NFSv3yy_base[NFSv3yy_current_state] + (unsigned int) NFSv3yy_c];
			*(NFSv3yy_state_ptr)++ = NFSv3yy_current_state;
			++NFSv3yy_cp;
			}
		while ( NFSv3yy_base[NFSv3yy_current_state] != 743 );

NFSv3yy_find_action:
		NFSv3yy_current_state = *--(NFSv3yy_state_ptr);
		(NFSv3yy_lp) = NFSv3yy_accept[NFSv3yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (NFSv3yy_lp) && (NFSv3yy_lp) < NFSv3yy_accept[NFSv3yy_current_state + 1] )
				{
				NFSv3yy_act = NFSv3yy_acclist[(NFSv3yy_lp)];
					{
					(NFSv3yy_full_match) = NFSv3yy_cp;
					break;
					}
				}
			--NFSv3yy_cp;
			NFSv3yy_current_state = *--(NFSv3yy_state_ptr);
			(NFSv3yy_lp) = NFSv3yy_accept[NFSv3yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( NFSv3yy_act != YY_END_OF_BUFFER && NFSv3yy_rule_can_match_eol[NFSv3yy_act] )
			{
			int NFSv3yyl;
			for ( NFSv3yyl = (NFSv3yy_prev_more_offset); NFSv3yyl < NFSv3yyleng; ++NFSv3yyl )
				if ( NFSv3yytext[NFSv3yyl] == '\n' )
					   
    NFSv3yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( NFSv3yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 46 "util/parser/lexer.l"
{
	return(ANONGID);
	}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 50 "util/parser/lexer.l"
{
	return(ANONUID);
	}
	YY_BREAK
/* The following lexical tokens return the token identifier and the value of the token (in NFSv3yylval) */
case 3:
#line 57 "util/parser/lexer.l"
case 4:
#line 58 "util/parser/lexer.l"
case 5:
YY_RULE_SETUP
#line 58 "util/parser/lexer.l"
{
	NFSv3yylval.string = (char *)strdup(NFSv3yytext);
	return(SQUASH);
	}
	YY_BREAK
case 6:
#line 64 "util/parser/lexer.l"
case 7:
YY_RULE_SETUP
#line 64 "util/parser/lexer.l"
{
	NFSv3yylval.string = (char *)strdup(NFSv3yytext);
	return(PERMISSION);
	}
	YY_BREAK
case 8:
#line 70 "util/parser/lexer.l"
case 9:
YY_RULE_SETUP
#line 70 "util/parser/lexer.l"
{
	NFSv3yylval.boolean = !strcmp(NFSv3yytext,"secure");
	return(SECURE);
	}
	YY_BREAK
case 10:
#line 76 "util/parser/lexer.l"
case 11:
YY_RULE_SETUP
#line 76 "util/parser/lexer.l"
{
	NFSv3yylval.boolean = !strcmp(NFSv3yytext,"sync");
	return(SYNC);
	}
	YY_BREAK
case 12:
#line 82 "util/parser/lexer.l"
case 13:
YY_RULE_SETUP
#line 82 "util/parser/lexer.l"
{
	NFSv3yylval.boolean = !strcmp(NFSv3yytext,"wdelay");
	return(WRITEDELAY);
	}
	YY_BREAK
case 14:
#line 88 "util/parser/lexer.l"
case 15:
YY_RULE_SETUP
#line 88 "util/parser/lexer.l"
{
	NFSv3yylval.boolean = !strcmp(NFSv3yytext,"hide");
	return(HIDE);
	}
	YY_BREAK
case 16:
#line 94 "util/parser/lexer.l"
case 17:
YY_RULE_SETUP
#line 94 "util/parser/lexer.l"
{
	NFSv3yylval.boolean = !strcmp(NFSv3yytext,"subtree_check");
	return(SUBTREECHECK);
	}
	YY_BREAK
case 18:
#line 100 "util/parser/lexer.l"
case 19:
#line 101 "util/parser/lexer.l"
case 20:
#line 102 "util/parser/lexer.l"
case 21:
YY_RULE_SETUP
#line 102 "util/parser/lexer.l"
{
	NFSv3yylval.boolean = !strcmp(NFSv3yytext,"secure_locks") || !strcmp(NFSv3yytext,"auth_nlm");
	return(SECURELOCKS);
	}
	YY_BREAK
/* Absolute pathname of the exported Unix directory */
case 22:
YY_RULE_SETUP
#line 108 "util/parser/lexer.l"
{
	NFSv3yylval.string = (char *)strdup(NFSv3yytext);
	return(PATHNAME);
	}
	YY_BREAK
/* Different ways to specify the NFS client machine name(s) */
case 23:
#line 115 "util/parser/lexer.l"
case 24:
#line 116 "util/parser/lexer.l"
case 25:
#line 117 "util/parser/lexer.l"
case 26:
#line 118 "util/parser/lexer.l"
case 27:
#line 119 "util/parser/lexer.l"
case 28:
YY_RULE_SETUP
#line 119 "util/parser/lexer.l"
{
	NFSv3yylval.string = (char *)strdup(NFSv3yytext);
	return(HOSTNAME);
	}
	YY_BREAK
/* UID or GID */
case 29:
YY_RULE_SETUP
#line 125 "util/parser/lexer.l"
{
	NFSv3yylval.uint16 = strtoul(NFSv3yytext,NULL,0);
	return(NUMBER);
	}
	YY_BREAK
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 130 "util/parser/lexer.l"
{
	NFSv3yylineno++;
	}
	YY_BREAK
/* Ignore whitespace */
case 31:
YY_RULE_SETUP
#line 135 "util/parser/lexer.l"
;
	YY_BREAK
/* Ignore end-of-line continuation markers */
case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
#line 138 "util/parser/lexer.l"
{
	NFSv3yylineno++;
	}
	YY_BREAK
/* Ignore comments */
case 33:
/* rule 33 can match eol */
YY_RULE_SETUP
#line 143 "util/parser/lexer.l"
{
	/* Extend the comments buffer */
	if (NFSv3comments == NULL) {
    	   NFSv3comments = malloc(strlen(NFSv3yytext)+1);
	   strcpy(NFSv3comments,"");
	} else {
	   char * newcomments = malloc(strlen(NFSv3comments)+strlen(NFSv3yytext)+1);
	   strcpy(newcomments, NFSv3comments);
	   free(NFSv3comments);
	   NFSv3comments = newcomments;
	}

	/* Add this comment line to the comments buffer */
	strcat(NFSv3comments,NFSv3yytext);
	}
	YY_BREAK
/* Return single character punctuation characters as-is */
case 34:
YY_RULE_SETUP
#line 160 "util/parser/lexer.l"
{
	return(NFSv3yytext[0]);
	}
	YY_BREAK
/* END OF RULES SECTION */
case 35:
YY_RULE_SETUP
#line 165 "util/parser/lexer.l"
ECHO;
	YY_BREAK
#line 1263 "<stdout>"
			case YY_STATE_EOF(INITIAL):
				NFSv3yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int NFSv3yy_amount_of_matched_text = (int) (NFSv3yy_cp - (NFSv3yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*NFSv3yy_cp = (NFSv3yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->NFSv3yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed NFSv3yyin at a new source and called
			 * NFSv3yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(NFSv3yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->NFSv3yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->NFSv3yy_input_file = NFSv3yyin;
			YY_CURRENT_BUFFER_LVALUE->NFSv3yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for NFSv3yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since NFSv3yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (NFSv3yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->NFSv3yy_ch_buf[(NFSv3yy_n_chars)] )
			{ /* This was really a NUL. */
			NFSv3yy_state_type NFSv3yy_next_state;

			(NFSv3yy_c_buf_p) = (NFSv3yytext_ptr) + NFSv3yy_amount_of_matched_text;

			NFSv3yy_current_state = NFSv3yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * NFSv3yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			NFSv3yy_next_state = NFSv3yy_try_NUL_trans( NFSv3yy_current_state );

			NFSv3yy_bp = (NFSv3yytext_ptr) + YY_MORE_ADJ;

			if ( NFSv3yy_next_state )
				{
				/* Consume the NUL. */
				NFSv3yy_cp = ++(NFSv3yy_c_buf_p);
				NFSv3yy_current_state = NFSv3yy_next_state;
				goto NFSv3yy_match;
				}

			else
				{
				NFSv3yy_cp = (NFSv3yy_c_buf_p);
				goto NFSv3yy_find_action;
				}
			}

		else switch ( NFSv3yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(NFSv3yy_did_buffer_switch_on_eof) = 0;

				if ( NFSv3yywrap( ) )
					{
					/* Note: because we've taken care in
					 * NFSv3yy_get_next_buffer() to have set up
					 * NFSv3yytext, we can now set up
					 * NFSv3yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(NFSv3yy_c_buf_p) = (NFSv3yytext_ptr) + YY_MORE_ADJ;

					NFSv3yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (NFSv3yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(NFSv3yy_c_buf_p) =
					(NFSv3yytext_ptr) + NFSv3yy_amount_of_matched_text;

				NFSv3yy_current_state = NFSv3yy_get_previous_state(  );

				NFSv3yy_cp = (NFSv3yy_c_buf_p);
				NFSv3yy_bp = (NFSv3yytext_ptr) + YY_MORE_ADJ;
				goto NFSv3yy_match;

			case EOB_ACT_LAST_MATCH:
				(NFSv3yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->NFSv3yy_ch_buf[(NFSv3yy_n_chars)];

				NFSv3yy_current_state = NFSv3yy_get_previous_state(  );

				NFSv3yy_cp = (NFSv3yy_c_buf_p);
				NFSv3yy_bp = (NFSv3yytext_ptr) + YY_MORE_ADJ;
				goto NFSv3yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of NFSv3yylex */

/* NFSv3yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int NFSv3yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->NFSv3yy_ch_buf;
	register char *source = (NFSv3yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (NFSv3yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->NFSv3yy_ch_buf[(NFSv3yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->NFSv3yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (NFSv3yy_c_buf_p) - (NFSv3yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((NFSv3yy_c_buf_p) - (NFSv3yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->NFSv3yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->NFSv3yy_n_chars = (NFSv3yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->NFSv3yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->NFSv3yy_ch_buf[number_to_move]),
			(NFSv3yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->NFSv3yy_n_chars = (NFSv3yy_n_chars);
		}

	if ( (NFSv3yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			NFSv3yyrestart(NFSv3yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->NFSv3yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((NFSv3yy_size_t) ((NFSv3yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->NFSv3yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		NFSv3yy_size_t new_size = (NFSv3yy_n_chars) + number_to_move + ((NFSv3yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->NFSv3yy_ch_buf = (char *) NFSv3yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->NFSv3yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->NFSv3yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in NFSv3yy_get_next_buffer()" );
	}

	(NFSv3yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->NFSv3yy_ch_buf[(NFSv3yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->NFSv3yy_ch_buf[(NFSv3yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(NFSv3yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->NFSv3yy_ch_buf[0];

	return ret_val;
}

/* NFSv3yy_get_previous_state - get the state just before the EOB char was reached */

    static NFSv3yy_state_type NFSv3yy_get_previous_state (void)
{
	register NFSv3yy_state_type NFSv3yy_current_state;
	register char *NFSv3yy_cp;
    
	NFSv3yy_current_state = (NFSv3yy_start);

	(NFSv3yy_state_ptr) = (NFSv3yy_state_buf);
	*(NFSv3yy_state_ptr)++ = NFSv3yy_current_state;

	for ( NFSv3yy_cp = (NFSv3yytext_ptr) + YY_MORE_ADJ; NFSv3yy_cp < (NFSv3yy_c_buf_p); ++NFSv3yy_cp )
		{
		register YY_CHAR NFSv3yy_c = (*NFSv3yy_cp ? NFSv3yy_ec[YY_SC_TO_UI(*NFSv3yy_cp)] : 1);
		while ( NFSv3yy_chk[NFSv3yy_base[NFSv3yy_current_state] + NFSv3yy_c] != NFSv3yy_current_state )
			{
			NFSv3yy_current_state = (int) NFSv3yy_def[NFSv3yy_current_state];
			if ( NFSv3yy_current_state >= 195 )
				NFSv3yy_c = NFSv3yy_meta[(unsigned int) NFSv3yy_c];
			}
		NFSv3yy_current_state = NFSv3yy_nxt[NFSv3yy_base[NFSv3yy_current_state] + (unsigned int) NFSv3yy_c];
		*(NFSv3yy_state_ptr)++ = NFSv3yy_current_state;
		}

	return NFSv3yy_current_state;
}

/* NFSv3yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = NFSv3yy_try_NUL_trans( current_state );
 */
    static NFSv3yy_state_type NFSv3yy_try_NUL_trans  (NFSv3yy_state_type NFSv3yy_current_state )
{
	register int NFSv3yy_is_jam;
    
	register YY_CHAR NFSv3yy_c = 1;
	while ( NFSv3yy_chk[NFSv3yy_base[NFSv3yy_current_state] + NFSv3yy_c] != NFSv3yy_current_state )
		{
		NFSv3yy_current_state = (int) NFSv3yy_def[NFSv3yy_current_state];
		if ( NFSv3yy_current_state >= 195 )
			NFSv3yy_c = NFSv3yy_meta[(unsigned int) NFSv3yy_c];
		}
	NFSv3yy_current_state = NFSv3yy_nxt[NFSv3yy_base[NFSv3yy_current_state] + (unsigned int) NFSv3yy_c];
	NFSv3yy_is_jam = (NFSv3yy_current_state == 194);
	if ( ! NFSv3yy_is_jam )
		*(NFSv3yy_state_ptr)++ = NFSv3yy_current_state;

	return NFSv3yy_is_jam ? 0 : NFSv3yy_current_state;
}

    static void NFSv3yyunput (int c, register char * NFSv3yy_bp )
{
	register char *NFSv3yy_cp;
    
    NFSv3yy_cp = (NFSv3yy_c_buf_p);

	/* undo effects of setting up NFSv3yytext */
	*NFSv3yy_cp = (NFSv3yy_hold_char);

	if ( NFSv3yy_cp < YY_CURRENT_BUFFER_LVALUE->NFSv3yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (NFSv3yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->NFSv3yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->NFSv3yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->NFSv3yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->NFSv3yy_ch_buf )
			*--dest = *--source;

		NFSv3yy_cp += (int) (dest - source);
		NFSv3yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->NFSv3yy_n_chars =
			(NFSv3yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->NFSv3yy_buf_size;

		if ( NFSv3yy_cp < YY_CURRENT_BUFFER_LVALUE->NFSv3yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--NFSv3yy_cp = (char) c;

    if ( c == '\n' ){
        --NFSv3yylineno;
    }

	(NFSv3yytext_ptr) = NFSv3yy_bp;
	(NFSv3yy_hold_char) = *NFSv3yy_cp;
	(NFSv3yy_c_buf_p) = NFSv3yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int NFSv3yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(NFSv3yy_c_buf_p) = (NFSv3yy_hold_char);

	if ( *(NFSv3yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* NFSv3yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (NFSv3yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->NFSv3yy_ch_buf[(NFSv3yy_n_chars)] )
			/* This was really a NUL. */
			*(NFSv3yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (NFSv3yy_c_buf_p) - (NFSv3yytext_ptr);
			++(NFSv3yy_c_buf_p);

			switch ( NFSv3yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because NFSv3yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					NFSv3yyrestart(NFSv3yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( NFSv3yywrap( ) )
						return EOF;

					if ( ! (NFSv3yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return NFSv3yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(NFSv3yy_c_buf_p) = (NFSv3yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (NFSv3yy_c_buf_p);	/* cast for 8-bit char's */
	*(NFSv3yy_c_buf_p) = '\0';	/* preserve NFSv3yytext */
	(NFSv3yy_hold_char) = *++(NFSv3yy_c_buf_p);

	if ( c == '\n' )
		   
    NFSv3yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void NFSv3yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        NFSv3yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            NFSv3yy_create_buffer(NFSv3yyin,YY_BUF_SIZE );
	}

	NFSv3yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	NFSv3yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void NFSv3yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		NFSv3yypop_buffer_state();
	 *		NFSv3yypush_buffer_state(new_buffer);
     */
	NFSv3yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(NFSv3yy_c_buf_p) = (NFSv3yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->NFSv3yy_buf_pos = (NFSv3yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->NFSv3yy_n_chars = (NFSv3yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	NFSv3yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (NFSv3yywrap()) processing, but the only time this flag
	 * is looked at is after NFSv3yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(NFSv3yy_did_buffer_switch_on_eof) = 1;
}

static void NFSv3yy_load_buffer_state  (void)
{
    	(NFSv3yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->NFSv3yy_n_chars;
	(NFSv3yytext_ptr) = (NFSv3yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->NFSv3yy_buf_pos;
	NFSv3yyin = YY_CURRENT_BUFFER_LVALUE->NFSv3yy_input_file;
	(NFSv3yy_hold_char) = *(NFSv3yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE NFSv3yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) NFSv3yyalloc(sizeof( struct NFSv3yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in NFSv3yy_create_buffer()" );

	b->NFSv3yy_buf_size = size;

	/* NFSv3yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->NFSv3yy_ch_buf = (char *) NFSv3yyalloc(b->NFSv3yy_buf_size + 2  );
	if ( ! b->NFSv3yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in NFSv3yy_create_buffer()" );

	b->NFSv3yy_is_our_buffer = 1;

	NFSv3yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with NFSv3yy_create_buffer()
 * 
 */
    void NFSv3yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->NFSv3yy_is_our_buffer )
		NFSv3yyfree((void *) b->NFSv3yy_ch_buf  );

	NFSv3yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a NFSv3yyrestart() or at EOF.
 */
    static void NFSv3yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	NFSv3yy_flush_buffer(b );

	b->NFSv3yy_input_file = file;
	b->NFSv3yy_fill_buffer = 1;

    /* If b is the current buffer, then NFSv3yy_init_buffer was _probably_
     * called from NFSv3yyrestart() or through NFSv3yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->NFSv3yy_bs_lineno = 1;
        b->NFSv3yy_bs_column = 0;
    }

        b->NFSv3yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void NFSv3yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->NFSv3yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->NFSv3yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->NFSv3yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->NFSv3yy_buf_pos = &b->NFSv3yy_ch_buf[0];

	b->NFSv3yy_at_bol = 1;
	b->NFSv3yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		NFSv3yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void NFSv3yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	NFSv3yyensure_buffer_stack();

	/* This block is copied from NFSv3yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(NFSv3yy_c_buf_p) = (NFSv3yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->NFSv3yy_buf_pos = (NFSv3yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->NFSv3yy_n_chars = (NFSv3yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(NFSv3yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from NFSv3yy_switch_to_buffer. */
	NFSv3yy_load_buffer_state( );
	(NFSv3yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void NFSv3yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	NFSv3yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((NFSv3yy_buffer_stack_top) > 0)
		--(NFSv3yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		NFSv3yy_load_buffer_state( );
		(NFSv3yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void NFSv3yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(NFSv3yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(NFSv3yy_buffer_stack) = (struct NFSv3yy_buffer_state**)NFSv3yyalloc
								(num_to_alloc * sizeof(struct NFSv3yy_buffer_state*)
								);
		if ( ! (NFSv3yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in NFSv3yyensure_buffer_stack()" );
								  
		memset((NFSv3yy_buffer_stack), 0, num_to_alloc * sizeof(struct NFSv3yy_buffer_state*));
				
		(NFSv3yy_buffer_stack_max) = num_to_alloc;
		(NFSv3yy_buffer_stack_top) = 0;
		return;
	}

	if ((NFSv3yy_buffer_stack_top) >= ((NFSv3yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (NFSv3yy_buffer_stack_max) + grow_size;
		(NFSv3yy_buffer_stack) = (struct NFSv3yy_buffer_state**)NFSv3yyrealloc
								((NFSv3yy_buffer_stack),
								num_to_alloc * sizeof(struct NFSv3yy_buffer_state*)
								);
		if ( ! (NFSv3yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in NFSv3yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((NFSv3yy_buffer_stack) + (NFSv3yy_buffer_stack_max), 0, grow_size * sizeof(struct NFSv3yy_buffer_state*));
		(NFSv3yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE NFSv3yy_scan_buffer  (char * base, NFSv3yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) NFSv3yyalloc(sizeof( struct NFSv3yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in NFSv3yy_scan_buffer()" );

	b->NFSv3yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->NFSv3yy_buf_pos = b->NFSv3yy_ch_buf = base;
	b->NFSv3yy_is_our_buffer = 0;
	b->NFSv3yy_input_file = 0;
	b->NFSv3yy_n_chars = b->NFSv3yy_buf_size;
	b->NFSv3yy_is_interactive = 0;
	b->NFSv3yy_at_bol = 1;
	b->NFSv3yy_fill_buffer = 0;
	b->NFSv3yy_buffer_status = YY_BUFFER_NEW;

	NFSv3yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to NFSv3yylex() will
 * scan from a @e copy of @a str.
 * @param NFSv3yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       NFSv3yy_scan_bytes() instead.
 */
YY_BUFFER_STATE NFSv3yy_scan_string (NFSv3yyconst char * NFSv3yystr )
{
    
	return NFSv3yy_scan_bytes(NFSv3yystr,strlen(NFSv3yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to NFSv3yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE NFSv3yy_scan_bytes  (NFSv3yyconst char * NFSv3yybytes, int  _NFSv3yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	NFSv3yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _NFSv3yybytes_len + 2;
	buf = (char *) NFSv3yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in NFSv3yy_scan_bytes()" );

	for ( i = 0; i < _NFSv3yybytes_len; ++i )
		buf[i] = NFSv3yybytes[i];

	buf[_NFSv3yybytes_len] = buf[_NFSv3yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = NFSv3yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in NFSv3yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->NFSv3yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void NFSv3yy_fatal_error (NFSv3yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine NFSv3yyless() so it works in section 3 code. */

#undef NFSv3yyless
#define NFSv3yyless(n) \
	do \
		{ \
		/* Undo effects of setting up NFSv3yytext. */ \
        int NFSv3yyless_macro_arg = (n); \
        YY_LESS_LINENO(NFSv3yyless_macro_arg);\
		NFSv3yytext[NFSv3yyleng] = (NFSv3yy_hold_char); \
		(NFSv3yy_c_buf_p) = NFSv3yytext + NFSv3yyless_macro_arg; \
		(NFSv3yy_hold_char) = *(NFSv3yy_c_buf_p); \
		*(NFSv3yy_c_buf_p) = '\0'; \
		NFSv3yyleng = NFSv3yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int NFSv3yyget_lineno  (void)
{
        
    return NFSv3yylineno;
}

/** Get the input stream.
 * 
 */
FILE *NFSv3yyget_in  (void)
{
        return NFSv3yyin;
}

/** Get the output stream.
 * 
 */
FILE *NFSv3yyget_out  (void)
{
        return NFSv3yyout;
}

/** Get the length of the current token.
 * 
 */
int NFSv3yyget_leng  (void)
{
        return NFSv3yyleng;
}

/** Get the current token.
 * 
 */

char *NFSv3yyget_text  (void)
{
        return NFSv3yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void NFSv3yyset_lineno (int  line_number )
{
    
    NFSv3yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see NFSv3yy_switch_to_buffer
 */
void NFSv3yyset_in (FILE *  in_str )
{
        NFSv3yyin = in_str ;
}

void NFSv3yyset_out (FILE *  out_str )
{
        NFSv3yyout = out_str ;
}

int NFSv3yyget_debug  (void)
{
        return NFSv3yy_flex_debug;
}

void NFSv3yyset_debug (int  bdebug )
{
        NFSv3yy_flex_debug = bdebug ;
}

static int NFSv3yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from NFSv3yylex_destroy(), so don't allocate here.
     */

    /* We do not touch NFSv3yylineno unless the option is enabled. */
    NFSv3yylineno =  1;
    
    (NFSv3yy_buffer_stack) = 0;
    (NFSv3yy_buffer_stack_top) = 0;
    (NFSv3yy_buffer_stack_max) = 0;
    (NFSv3yy_c_buf_p) = (char *) 0;
    (NFSv3yy_init) = 0;
    (NFSv3yy_start) = 0;

    (NFSv3yy_state_buf) = 0;
    (NFSv3yy_state_ptr) = 0;
    (NFSv3yy_full_match) = 0;
    (NFSv3yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    NFSv3yyin = stdin;
    NFSv3yyout = stdout;
#else
    NFSv3yyin = (FILE *) 0;
    NFSv3yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * NFSv3yylex_init()
     */
    return 0;
}

/* NFSv3yylex_destroy is for both reentrant and non-reentrant scanners. */
int NFSv3yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		NFSv3yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		NFSv3yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	NFSv3yyfree((NFSv3yy_buffer_stack) );
	(NFSv3yy_buffer_stack) = NULL;

    NFSv3yyfree ( (NFSv3yy_state_buf) );
    (NFSv3yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * NFSv3yylex() is called, initialization will occur. */
    NFSv3yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef NFSv3yytext_ptr
static void NFSv3yy_flex_strncpy (char* s1, NFSv3yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int NFSv3yy_flex_strlen (NFSv3yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *NFSv3yyalloc (NFSv3yy_size_t  size )
{
	return (void *) malloc( size );
}

void *NFSv3yyrealloc  (void * ptr, NFSv3yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void NFSv3yyfree (void * ptr )
{
	free( (char *) ptr );	/* see NFSv3yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "NFSv3yytables"

#line 165 "util/parser/lexer.l"


	/* USER SUBROUTINE SECTION */
	/* Everything below is copied verbatim to the end of the lex generated C code. */

void NFSv3yyerror(char *errmsg)
{
   fprintf(stderr, "NFSv3 parser, line %d: %s at '%s'\n", NFSv3yylineno, errmsg, NFSv3yytext);
}


